apiVersion: v1
kind: Secret
metadata:
    name: garage-admin-tokens
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:+rUk2la0pW/+Uo8F6ElFy0tfznglCRz4PM8sb6iZxXrokzM6d0pE+L1esl+GNN3I,iv:sfxTJEq0wpPjGjxIPCH/WnPr/vTp0NzLVM278t4X6+Y=,tag:o+aFZl0pkNmUxBQfGN8QWw==,type:str]
    metrics-token: ENC[AES256_GCM,data:a7HOkuytZhX7SOWGp1MR2movxWZwZZx5QiilnOdc5ynTTM1XiOqbnX3Pt4Aociot,iv:6gJRi81ttZvjlNYZFI2NfSSzkztSRMshrnT3B6FaTOw=,tag:HSCXCgEAVyTTQkCr36plDA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5REdLTUd6UklvV25JSm5O
            bEZTaW5wWUVJV2lwUHFZdEdrZU1KVWcyUGk0CllzZm1HaHkvVlRCZUc0T3ZIMytR
            allwRFFuWDJ2MlRQQmQ4Mks1WUM1RzQKLS0tIE1IMWljY1FwdDNBZFNyNlQyZ2pU
            Y1htUlVFZjZCcEY4cUNSTUN1QlRFZ1UKAfXEpEp51XvV6Tz/vrxAyorMX1RKsyGl
            r7HQAwRbe0YrDtzhrsfkC1OUNJol4oy+dwsZJpgYnUN0UWqt/bYJDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T12:14:53Z"
    mac: ENC[AES256_GCM,data:WYzcIATDuL90l7R/OFkzC49c5JTE2HQqr7sd2HThWTSPl70Odjembg3czQWefV+KwHxPgtTVFzTusfx0i9B54cOLmDBjjrKY1+8cRBY6ZzKPO3NdZM/oUGbsyZ+4TVXVlFZiFH+zsd7TSk4zPWUUzy0dfpMpd4OLPwEr1efHCrw=,iv:SIRmgH87meOXfZdGEYdO0h9NZF6yauqnlpct1ha1xO8=,tag:lJpaLQzl7XoiIOXAusDUGw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
