apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-keys
type: Opaque
stringData:
    LOKI_KEY_ID: ENC[AES256_GCM,data:cKFmR1+jkfWdxVhDNaDWJhEx3UBUvWydl04=,iv:xHKsVwtIFf26yFypNBGOg3KZaYvVjLwNtMB39Ehxly0=,tag:ITfMzAfB1FX+oa1GFodBsQ==,type:str]
    LOKI_SECRET: ENC[AES256_GCM,data:YjlJRQ+BmJd+ODOv1eeYgt6ubaTmhb2zlc/oFZzANl0pqnuLkFpzT4KNSJpVZT8Dw34J4J0RJW66Ei+tEJaWJw==,iv:Hos6OZFF7WssHEzlkrlrH+HvcV8GwR7Ra5XeW3Zjb48=,tag:Cxn07ybLlvtiLfqQZKephQ==,type:str]
    CNPG_KEY_ID: ENC[AES256_GCM,data:+Pf7Da37nf2vY4wjhB9K5t2rqv3je25qkII=,iv:ptps8l4F3/N55ZQN98Kt/Yi8vXYajfE8VFGnUnyCc60=,tag:mcIr1f+E9QWBOcZmvxwQYw==,type:str]
    CNPG_SECRET: ENC[AES256_GCM,data:XoDYpUE1K+rcWQK84RBBfzZ2PX5m0oBR+UJPLPGCV/2S/ow0akVDbTTp5RAs8cWKRUXV4MQnApx5KkSLMpr/dw==,iv:2Ygh+INVBz/dgFW4AbRd9Tm/Lsp2ND33HnqUPTA65FI=,tag:k5DHMrNpsPvOeIhR+d5OdA==,type:str]
    VECTOR_KEY_ID: ENC[AES256_GCM,data:wom6YH/eMk9seKrlhnvoGrEhi5HhQkuWl3o=,iv:b/ZB/uCKj7uwVklFBVKmuBT6k/j0j2AVsPm4sWUhDU0=,tag:VvnynCPIpLx5ZpKipc6sUQ==,type:str]
    VECTOR_SECRET: ENC[AES256_GCM,data:zndJnT/mnkmaUXWvdwWBR/wP5wwbjQ9KMcyNlKAFi4qKbVP2mEtbQLsWbMip16XT7bUWsumuJ2mcO5tgA+XXsA==,iv:/eoSstgKYS3KOMTt6hnZze4FQtzqFcN+L53WzxLVVZQ=,tag:xmCePeC/e0e1MZjhC670oQ==,type:str]
    COMPACT_KEY_ID: ENC[AES256_GCM,data:BJDXIBynPuL8+1m4Xl0ZcSRhBZWZ1TXQ3jg=,iv:T0z/WqJ8Mc5L3nVa1Az5FzLfJIcLLD5aX5w01kudrhQ=,tag:858rtdSfKk5TEavhQDDDuw==,type:str]
    COMPACT_SECRET: ENC[AES256_GCM,data:JpJ2ZmepcX3cOWhG6AVqK881MLYyQY/s/w3tUTOl7XL413ORbQLnPyp4RNNDE5ifT7ax+mHdgx0UJP+d8ygBGw==,iv:v61fCx02+FIAsnlzJLC4eSI1p6Wq78JuUgQv/6kuL+A=,tag:EsfU9AUkm9deWVTRCjWkYw==,type:str]
    GRAFANA_DUCKDB_KEY_ID: ENC[AES256_GCM,data:NTbcVac5HTMCenqzefrgrLy+70JCxjAZNJ4=,iv:wCJi7BamftZStGaNE9u0QfStjxdDd84vMaR5JTSAlhw=,tag:w8+qOcXidG/j/qT9xybV1A==,type:str]
    GRAFANA_DUCKDB_SECRET: ENC[AES256_GCM,data:AlDjXSeN2g389ZGMkesp3WsjU45rCJKZtvdl8gS3P1mvx3qgl9qlg4YKfMwUC2kutrkJV/2YDyTaxOu+evUtgw==,iv:ahoueEfi5CVgtouZpW4UO3nyohB1T7KKBYatZczKTdU=,tag:Qp/x3laA9GzB+plgC9KPwA==,type:str]
    LOGS_TYPED_DBT_KEY_ID: ENC[AES256_GCM,data:iPXXFNvQNOi0ly5NZ6Ycm946G1qpvP439Wk=,iv:QK7qbATj3RH5vusPl/E5vdOQ9snjpZmxkoAJgp4XI8I=,tag:7I4IsISzzIGMfqk1KUoo7A==,type:str]
    LOGS_TYPED_DBT_SECRET: ENC[AES256_GCM,data:T+INWp4OM+MC0fjPYEQ0tMc5TA4bgAo4UZy59VrtWasmK9j/pFZh/Fr1hOdqK5kgIdcNJks0sbX5xNz9wlkO4g==,iv:ZGjV1BXDGz2LpSwETLck65WxCK5f4z5MO09I6PejHQo=,tag:Un1IiiiPFxbw9qtQEzlRrQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRGo0RmRab0tkM010Y084
            UnJsR2dlSW9ycmcrK3Y2WXNYK1RReW1vb0IwCjU5dGdqUHlCSVdnZzhGZ0lWL2pD
            bmZwMi9selF1U0ZCOHJQYVQ3R2dOUWcKLS0tIEdvMmhoeTduWE1rRWFQaUc3cDMv
            bkc5MFZPZHdQcHRFcVR6alZ1UzZ2alUKgMfF/sjBpQf8tGpFdcsnMkzf63MAAABH
            xpamwgDgUfJR8b8Qoo/pYgXcoGwsN8M+pSUC5jxI5oi5JD6W6DPmvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T09:03:21Z"
    mac: ENC[AES256_GCM,data:KeSi0Vfz+rr+DrInyhvmXjdw2myLJdZch9UtbdeWTTbgcNLrG5u+zWLnz9r4EphtesRH5M+oc1NMCUZtEWThQWsZvF0dJ0KN57U6WkObHtvqw1RaZuEDrmI12U/58EL8XD1cvAO0+ZzliZE5a+T05Uvy3VLHdZ7S+ISTFDFpK84=,iv:lkRT/k16CWsOMrCErm2xW4mrGvxpqFjPU1tfiEtmTl8=,tag:VNoWEcGscpabctfxBsjMEA==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
