apiVersion: v1
kind: Secret
metadata:
    name: garage-obs-admin-tokens
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:M/M14/sLb5or03jQkJW4C/yntfktQ/Cv+TxHCyTKMaYP4VQWavgHZm8kajxDtc14RD2B/XG4Lvf9Uoould6deA==,iv:uwRpKosN3fAA99XVKhJOA6VWT/KPOZjZrND0gycsZeQ=,tag:CS1I8EwL/g2f0Hhwv9UU3g==,type:str]
    metrics-token: ENC[AES256_GCM,data:65MlPrbfSWB5unkmGePRl9NS54RAMDwlgfI8C2wVnWX+ENTYvorD+UR9GRY/mnovJt3Cs8KJWRTQhNuzQhPR0Q==,iv:n0uLswwfllOYBnglhUve3OUMu/IVTPr+shB2GhmZ2YY=,tag:gcS0hUt6/9p8igA3dccD1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUanNuUVBLME5FeTNaUmlo
            djB1ZEV3b1lVMGlNWmx5WTlyYTVycUlITDFrCmlyMS9Wc3JKSlJxc1J6V3FoSG9W
            R0lNakNYYXlKSjBYdGtHUWZEZlZRUkEKLS0tIHRqVnBuMmdyRFE2TnBLUzA4KzFO
            eWI4bUR5VjZFQUZaUGRSOFdDSEErY0UKrRJsNdYr+4IeDsBsb9azhbjBa6ahaQ2S
            WcvkTKBlgNGmxczAJqEIc7QUN569iAi8xkZdwtt44PKo0x7mafJK3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-23T12:49:19Z"
    mac: ENC[AES256_GCM,data:EK4wPW3CbqxaEzakJosszSb0HQbYrkErtnXTFkC8kZgUWJcJnhE7uMWKbvwYWFfJXZ+ANVDYIlgr2qvW+vtXyGcQ/n1C3p/OmT/91iQ9Wx5m+UyNZ8CiIZDyG2jgRjqsqY/4I0SUyKU8VEeOadEo7CUNLTmu4ewKANrl/wuh66E=,iv:GHLhrEPKjoJtu6cew+rjadmccbkRYnvg7jfin3Y7cYA=,tag:Hak639ck2iPfmsF2o9um5A==,type:str]
    version: 3.13.1
