apiVersion: v1
kind: Secret
metadata:
    name: garage-server-secrets
type: Opaque
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:JfMRBptUsDQBjetfZSA3wdRnMWfWwf0so3Pylqq2HZeObWAL+rUO1HrTLQZLgGY3fXloWUwyC2CgEbhhSIY8YA==,iv:/zwvt5Si0cY4WDWYajLTmdK6xkfevnvLP0t3ckNPGI8=,tag:AYgX/TNSepuykZZvm7yKew==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:8BEaQ6OXmGb4WpSXoMv9dG0P/chS1GMTzZdlY7M7xBJS8nSmY87cUmrqg7w8Cyw2,iv:OX0rno9vFEAJ3oQZDAuQWPr1PA5P7yGPgOSzc98sXkA=,tag:zC8D039qyD2Jsl24Tv38oQ==,type:str]
    GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:+Ix9I9Ltwvz70hQytKDz6fZwjoApUZFamD7HyERQOczqIgZy/b1c/1s5SAGgd+jT,iv:yRydxGQwyW3zw0Nn1sOzb+6fnrkfrPTDqdSfXaTIMuk=,tag:SO6KMeGmUVGRcLmyxlb3EQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2JSZlZYdldqVWxmNHhH
            QkpFMG1DdEVJNkJWWnBuR2poUEQzeUVEK1FNCkFDa2g0WGNrV3diL2U0ODBoZ0I4
            a0pscVJockdKd3QvMElSbWpXejRncWMKLS0tIFJDT2QrNG90MDNMT1BBZlFHZ29l
            eFNYRDV2ZjFWN1F3U0FLcXdzQTBnN3cKx+BGBuuR+EV/mfeYt+T9fRgQ6UN0Enrg
            ye2rfXPTImiwtbDxS9Lq1/F8Nb6TIV0G09KePeB5jnHOEMB5WTaUag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T11:59:13Z"
    mac: ENC[AES256_GCM,data:PPegNDcCD/ed2dwh5DK+U1bNfN+b16+OlJaCwNJ5m+uCsOjm6Fs1g4YQaHUwZhmaDrJG0sdDR9bsx0G4jhN1FjJ65nMy4XdROqCrfxLBZBsgkQJkyg77X6bUdfYHUU/EJQmwjyKsie5ktvq/PjIj4YNrjeosNvE3SY+VxfDNR2Q=,iv:fFbaDFn6wVnvPXPsxydnoFJB+NLlcI+mHt1wSaplINE=,tag:uu9E8JbS1u9XAU05ms5iCg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
