apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-keys
type: Opaque
stringData:
    LOKI_KEY_ID: ENC[AES256_GCM,data:ol9OblNFR6nrrKsBIVaZM/hbZsw=,iv:JkR5S1T3BNqAWfYax8p1/L/cCURyNCT/+V0DWuML/wk=,tag:vNTN79547ASAMD5wmqGG3w==,type:str]
    LOKI_SECRET: ENC[AES256_GCM,data:KwJf/pZyDS+j9Zdd4VV6PoWSoYiHF8yjyKguDyavvI1VgE9CQDYZsw==,iv:+5rb77+bqkyjw32waHd9RyC70eiiiaolG9K2c4kJ+YM=,tag:os5iU9BEtMO4B1u44DUCvQ==,type:str]
    CNPG_KEY_ID: ENC[AES256_GCM,data:vnVbTS5c7Y9MmdPj3BABwX3n9Iw=,iv:2n4htsHAtBdIMfuTXIcEzhGWc8kwAVdG1uH5neIVh64=,tag:4VQfIyrOBvrSlrJlVYtoKA==,type:str]
    CNPG_SECRET: ENC[AES256_GCM,data:LtAeJvcSBT0ojajc0GQBReJNRwb5/uOFPDtOYghElmSm1XZSGRYdpg==,iv:smQWuHQ+xc8bhaLgFgwIlzPvGocehqmRZw7x7GC4dgw=,tag:jewE/41i/EJBRBIrM9YP3w==,type:str]
    VECTOR_KEY_ID: ENC[AES256_GCM,data:eqcMV1Mgu8m0csP1bAMRvEKRstw=,iv:8RoT/6/3IMeV/FlM8se7v3EG492Wcbsf9nNVnKXpb1Y=,tag:VNIWQ2M7CARsHkNoLAINsQ==,type:str]
    VECTOR_SECRET: ENC[AES256_GCM,data:uiDSdVmcmEBoQxWZP1tZu4QICRyQt3p74G7EpkFA2porEgoDHQJuhQ==,iv:tRj9HHsD6xqR2OWJyLVXTy+FDzLT5q2CODBYkttv7Po=,tag:4YdTqgHi64RJa4WCZ8BS5w==,type:str]
    COMPACT_KEY_ID: ENC[AES256_GCM,data:s1z5dFMvqvfJfZjbgDNYFCrEtuM=,iv:JGeU1qKk9agImE9AtNSvUjVlSEVnDtBnaNEZMBJQgb8=,tag:5f9YkFPTMY3iPQ1bjr8bFw==,type:str]
    COMPACT_SECRET: ENC[AES256_GCM,data:YnBgGszIBFsdUYhgATuXpJRBZaMVWh9vyhDxRV/tkBiE2yoKXiQhww==,iv:csfMdqjSpVJ0gmqzOugrwGBclOgg3fMaIWVQwzP1r0A=,tag:j+3rH7OzvRtOQxQo3XmFmA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU0VNUHk0c1VZdFNWWVhs
            QXlOQnhzVm90NHVoaFExSDZkcWNNWjkxU2tZCkVDL1V5NHhlNWZRZFU0YnBlZ0Ji
            aVBwY0JiSUxpYXpuN2ZFZ1F0YWdpSVUKLS0tIHFNd0ZCUVZwMnVFNTcyYnU0SmVF
            N2RaRUowWlY2WTNMc1pxSTRmUFlGUFkKGPUmojwHcoHzvVZY4hdS9U2frkx/uiVm
            rsVt/r93iBY94ry9lQ2NOcvdtl5fxBbzKQdSp2CKyJ84OjPQx02B2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T11:59:13Z"
    mac: ENC[AES256_GCM,data:/GXONO4ZQD8ttavb0SkIGOTuagEHjfaZmJyeKQ95oHJ/Gt3mu2Zg3sfw93tTW/MKhQDtoLEA/i0fL3DXe7DPKcRQe9izEn5jWII37hkT2i+oEwlIfN5QHf6gAUvSVkye2Ljo7q9sDfJuvMlPs5Kpd7a8617QT+TUHzlpI7HSjpQ=,iv:oxTkHIuqKNCqG9PD9CRKI0nSVwWfWI10nE6I5qkb4/c=,tag:FAMkrvCXrf2OOmAYCRLuxQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
