apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-keys-authentik
type: Opaque
stringData:
    CNPG_AUTHENTIK_KEY_ID: ENC[AES256_GCM,data:XQjmM8q0BLKmenIuxB+WiRYlXntw+fvRzck=,iv:2ZDKyPWLT/M/7JfSwJH1Ykigw3i0CIi5PjsLi69qqII=,tag:AE6OoJAnsaAIRBPXWnM2lA==,type:str]
    CNPG_AUTHENTIK_SECRET: ENC[AES256_GCM,data:SZhcfxBtnsR9ubdDXVXOEc8dOdXGV6OEoYqk4VFreFmajxdISDWwRvY+9esRS2hk2S2w/s9bMAeNMIXfKw2V8Q==,iv:zeuuaw84yMgrW7NnTLDJAb39uk046odi76fqvYyTx1Y=,tag:K/8CZ9GJB1L8J88ps7B1yA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bGZycjNEd2owRlhvY2FS
            ZHkyL2M5elhMa3N0WFJ5L2lRN0ZIbnVxWFFRCk94ZTFSMGt3S0wyVWVHN3ZUemhQ
            RDFVd1I4YStkYURwVVgva3crT2llQmMKLS0tIGM5QmNzQ0tHQXAxYWFvRXlRSmZn
            eE92VTN0NkJSMnVBWFdBaktiK3pPd2MKtrUGftHZSRnPDBJ2BQsDX3ogh7Y2Ixsd
            KXXoG5kC1aC9MD4157w61ARhp4X1+7n+IRQOWRqLg1EDQqUITcIwAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T14:48:47Z"
    mac: ENC[AES256_GCM,data:gpMorP8IEBm7RkuhVGL92rNmJ1MrMIsWq9pVsDdgzXX/IPgDz1UIbjU3krpjc/VA4JT6LfvDjptci2kXBpfmK6vZ9dlCz1RwB1f36T4WSMtIaWVevwkE4ZoBY6t6yZSLYyJiptq+mfVY8NqLw8IahcagAC/2xzYI+oBYrbOBLHk=,iv:7PjfHMfkbQ7pvn65PYBtmRIHAFcm6kj8VTjawCUKppA=,tag:wPoM+1ZTjqpl0ImSlA1Efg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
