apiVersion: v1
kind: Secret
metadata:
    name: garage-archive-admin-tokens
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:f9IQzOVOA6oU4tH8OsI5hx9CwmclbBRTlBASxwlAeIFZbnyugVKgtKVggqZ7nnWuDXnQb7fViwKJKoVnC79wLw==,iv:tuNo956YcsBK86Ikxz0QzV7b/M17uKcIwQffVRkBH3w=,tag:Xq7W2U+3DTPnoHoR4SGV1A==,type:str]
    metrics-token: ENC[AES256_GCM,data:xLJdGYLWB+uSdv4UkcgLcQuVMFB59VCDjHYPYPRu6d30GkxLCegqvSpFuiAIfF14FTlqaD0BcYd5bX1GGIFpQQ==,iv:mBgjI82VYJNJf22MaSzMH41wTxmCrbRQB45ppqYOqNY=,tag:rcz8P8GOQll8YQtiaOhGIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWkRDaXAyb1VrZnY0STBj
            UDZHMko4VXVLSmJxaEEvVUU0aGlRcU9XNm1VClhMQ2ZpNWxEbTUzalZXT3RKR1R6
            N3RQbVNYZGVEZEFBcitRWVlVL0wrN1UKLS0tIEhtY2dqNG1RVmpieVFFSmFOb1g2
            MHlldkdiZ1MxdHplOFhzYk9RSU1KeFUKtLzmWH+7Igseerzhd5kHvc2Bzg5v0UDe
            rLEADg4AnVEiSxFJ2lLR/fOUemvhkZmu485hZcxPu9n86nCe2uXfFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-14T14:16:24Z"
    mac: ENC[AES256_GCM,data:DIgI1Q89c1cpA6SY8RtRbZbVy8E1G3PO6aU4PL3V4zafSregvGDrQW1bSusgAlqCyf4VFNnicTjd9DBs3riCK8cQp2HgGyzJHivJLKiGoL+w3hSHO1Ls9oQtlhWfuYZJ0DmlFam2blzPUH9jVXYcSj5mjc8oMupH7Rc95vhUzCA=,iv:qcGhjnXq1rhR+IFBlXswmHwa7dbwJIT3Nk3dEBUHaTk=,tag:6PgTin/oEgVAvIJvJtesaA==,type:str]
    version: 3.13.1
