apiVersion: v1
kind: Secret
metadata:
    name: garage-s3-keys
type: Opaque
stringData:
    LOKI_KEY_ID: ENC[AES256_GCM,data:dbHqy2igTfaNsErEfhmUioM4RHfrf4hFSng=,iv:Evh2w8KOdhJA8YC1gUuvCs1ADy/AwB7id4MmGy0IWVA=,tag:Ma+MOpcCxYoU7HUWN4Id2A==,type:str]
    LOKI_SECRET: ENC[AES256_GCM,data:QUX9CPj4xL+Z2Bya5KcdFnRK79SFVuhAuQU2BdGDbQfo42FAn/vZJQ==,iv:2dAA8Sf33nB6dYtuKNUFN8Gvh2ftRzk92RSwPfhj8Dw=,tag:sFwCX1c8kLkOkZMUvxoBOA==,type:str]
    CNPG_KEY_ID: ENC[AES256_GCM,data:N6T7EF5L2NGpphG1QMJlA6iYItHIf4UX3hA=,iv:ZAAJaZtCvgucxs9qbX98nNNRL4zdodCBd8PV08xTAZ0=,tag:L12NPYupT2LYlVSpan/OHQ==,type:str]
    CNPG_SECRET: ENC[AES256_GCM,data:gEsgIDHWFvdAPVTYtRimOn3s9GMGDrlD3xqkOLvvKqt1OzYJG8zCzw==,iv:8MdAZBRZfbiBOTQ2wbVLUK8M14LP2fDBHbR6+uARt7M=,tag:8WOW9+yMNKoLywyqh0Ay2w==,type:str]
    VECTOR_KEY_ID: ENC[AES256_GCM,data:qYjPsQQhlMcqbHrA3sEIsZWXQlnzMBcchjc=,iv:8Hathfg7Dk5o2TllCwq7Wis3jfuRXbiuFLA/E1+I3TM=,tag:X7V1L6c1oprKgn6YufzfKg==,type:str]
    VECTOR_SECRET: ENC[AES256_GCM,data:ZeF6ckm43eBL+6SQvzm19oQlUR7gvgcpczXP9Fi/BTjEhzmkA8CKjw==,iv:ZuX7oQHL+AompxvbfFfBwtVqlhgMlygRMip5ODCXCeU=,tag:y1maMZLyhe6MtkC7dcI3xw==,type:str]
    COMPACT_KEY_ID: ENC[AES256_GCM,data:x6UR3rhGzReRPkVk4s0Mobhh96XIiN6oUiI=,iv:iMBKcBJgFTixF0Mi1Qhq5z3hAKcDeCrVyX0NxONgfs0=,tag:ub5vUVhY0371b79GIVs4dQ==,type:str]
    COMPACT_SECRET: ENC[AES256_GCM,data:g9JWzGCbQcPn6EYPQFJtwfUInWHvJxEpidroF2kOGHNiUxy0iR17WA==,iv:lj8wObUqkwOBAy3N6pBjT7Tyxu+w40CEGKOrfrwR8jQ=,tag:YqDrxCwm59DsBGhaddTrDA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1b3J1dTB5eFJSeXRTTXBx
            MUdib1Z5M3RpN2NBVXhyRTQ2UWYyZmFMeTJnCi93cEJtZ1RiVDZvNG1lMVphSHN2
            VmE3dEZnd3ZDelF0dEdpbHFyVkhNR0UKLS0tIGxWdFdVMjZkYVhUazk0YkVDRWQ5
            QWYzaGp5WDBNamxOWXZIRFNMQy81SzgKsJTImwzLBq7jbTlyh7hD05kNZdqKGTaL
            6t1Zs/HRCAY0l+GY3i4ElLY+o6PC3tfzJCMvEsBeXXSEcSgCGXWrwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T14:25:57Z"
    mac: ENC[AES256_GCM,data:rrE9kZ4q0F0ewj020EbYuTGifBKiJLNn2PmB+guJFEQYfHFd0nA5+Aa9wC0lRw4HJsJnFCw5afthsesdU5yUJ9WeCMNv+QHGcesPjHl3/X44v0wdpXR4s3ZP9XWPHAPwtW7l8cSsvxHy+1X8d2Sh7bnKcAQZkpJwLrMjFP8mCuc=,iv:a43UUJOzPlUzMprUFi+2XeZDhVtN1yOoS1eas+MO+WE=,tag:xqbBoJRurI/oRNmsKVC1pA==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
