apiVersion: ENC[AES256_GCM,data:HWc=,iv:BvmqMrYqAjV2mVao7fpCi0VHno1VoTzNi/aUC/TBglI=,tag:AWS8UhXGPuLlW0riMdOBXA==,type:str]
kind: ENC[AES256_GCM,data:IjRVQV7k,iv:ebI0Jwm162T4lETb/ISHjOGqBkaY5VWB58N9Zh798os=,tag:51sOFx8fbRdZPUWSoT2m4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:N/QymtRn7WKiF5mZJaruvFcXAfYp,iv:orG901ZqJUMzT5yChWyKknwG1Rhc6EWhV/KTgrw9R9M=,tag:JahQyFP1cK6328m6PXWUug==,type:str]
type: ENC[AES256_GCM,data:+qjgj6Ou,iv:iECPu3zJmfQ/clS6a/1OdSFJHn8ZAfX5LNpIkZPsAfM=,tag:D9CCpQObBrB/7nCv3eKEnQ==,type:str]
stringData:
    #ENC[AES256_GCM,data:eHjlcCnVQHlG9eGyHJOYdXbxeTy5vZfRehFU236YPCP2uDD+iI2QPF4WqpFfjZw55HNBuRMIiL2XunUZBsT8mTAHafScsIpiUpvopZjecw2S7PYw32qwbLL0+cYrGCbzm1Ypmd5oXA==,iv:TmXCbBnKu3youe955dvIufQYiM3uC7mIPhY8xSDn4LA=,tag:yS1BXJ2sRpDjmUyZc0fTTA==,type:comment]
    #ENC[AES256_GCM,data:SzuewhP2Hj/0J7SK+OL0w6Do9VAKuA0g5TPSKE/+t9spc6aZCX6Tf91nVxERDBmGXNHn4q01KWuSrWPZ3cBqAR7BP1YUMSmNiMJEsqkcjJBSza6kpOQFPBw/Y8aTWfaAJJ5Oedr/CrGiwWI=,iv:O2h0No93cqCRfs1DTYIgR/VWOsfCrdXQgw00b/a+mLA=,tag:DrrtFR2QOtQ4wN9y6CunLg==,type:comment]
    THREATFOX_AUTH_KEY: ENC[AES256_GCM,data:YqPZQoFDUhuM7g3elXLjjU0rJ1P+,iv:gbmZ4P+am0B1+3TpuLgJernqmrGRhK6gg2X24OMDe3Y=,tag:SS2fLuaRtkWNCd3xW8NjCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRHJCTWNqZENRWjAra2ZM
            amVoOFM1TDkzUHh6U2pRVU1YTTdWMEhsMFQ0CjM0UGhJL3JJQzlQRVZNeVNQVnpE
            dlpGdjE3TGpKMTYxQzdJQ3V6Zm41ZzAKLS0tIGU0ajh0QTZlV1lHcnJjVWtGRnlB
            VmE2RUxLdGVDNDI0SStCenIveU5IalkKgMCBrF7JU6QZ993VVJyIvZ8/AljARtR3
            eMeLfPGAGP0jQhvzcbbgG3YZsNhy41A1D8DbJYa/jsATSntT3RbR2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    lastmodified: "2026-07-02T08:30:20Z"
    mac: ENC[AES256_GCM,data:Fsb4Sp+nljEqguLm2fvvcV712urqEXSlP3+vByIkgBUp/2DcepofHCgL9sILnHIWXuFL8sl7T//AQK6lN9SXej3eWyeckTfwKx8fCu3Z+8gQXLZaD31Dh4mDcsr6xz/Frxy96ixIV0zzak6rz5m+I7VRgdi7cI4cUvW6JX6N/+A=,iv:+PJYhv0y0CzZHXT40uGbkyt6KIH70yQzXCN7+6ZNbRA=,tag:MYiHUhTinOwcml2QVwhvTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
