apiVersion: v1
kind: Secret
metadata:
    name: threatfox-credentials
type: Opaque
stringData:
    #ENC[AES256_GCM,data:+BPOyvFbOyzLWzf2/iThRRTK09mG3B2QZ3SdJZ1vmBpYiB2Q+70Fh5HqYHomRU1uaB81Fh4Axru6u0Ptvi4UlqvMwjUnp+uX8BVh6hHCh5ahZhY=,iv:2pePyOzKih8Pe9+rOFwQvqtfzzXBovqPr6d2r8zYa6Q=,tag:Tb1qCwCDLG44dv/NZfxumg==,type:comment]
    THREATFOX_AUTH_KEY: ENC[AES256_GCM,data:B6p7DWTYFyChy3fohqWnsFkF3v8nHn1MiKyguw2IQLBRtTzf2wrngrQRehRdXxrU,iv:tX2Xxx/XWwT8B5ksT/OtjUAD1GT/5FGKEYy/l+2ahDw=,tag:88715JZXdNARB3jrUc38Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2hjMlozOHpkQUk2MnZ4
            TjBsbEJFUGsyWjB5THJQUTBJclFjem1jd1gwCk5FQ1RDeGhzMnpsdlk2aU1PRHph
            VVhEWmM4MDBXcWQ2YU1WeGxrS2VUOHMKLS0tIGJsZzJyNXc5c015WXFIcjB1UENF
            cERhYkRuMXZRQytNeG1ZY00xL0lNWU0KPv+SlSCwZ8j8z/3Jx/PHy0K8p4ixynn2
            14l3NiSnuVQvOOMhb5RtF0tVfp1VR+UIKILTNO5qpJQW485m5SseNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T10:17:03Z"
    mac: ENC[AES256_GCM,data:Po85Kog9X+VXJLXorzcm5ZUtBZBWsijyt43G4KxCo9FnFqeHrJn+/GJ8YsHt2Estk7+JEGatyjfqKKylN4gc+iKRqfuIDpZxRvh/CW2XA/acOPgUBTndsJt2TFMHit9ysF8ubX9kh8IWFw2H9s6upAj8wjcpa2527uPMhNZ+W/o=,iv:QfPw/z8aNvNbLXyQSiNdX6swEYWrQvsAClMgEuv+vwg=,tag:vdRhmnUPhwWmAKPhDxokOw==,type:str]
    version: 3.13.1
