keys:
  - &k8s_key age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
creation_rules:
  - path_regex: apps/.*/secrets/.*\.enc\.yaml$
    key_groups:
      - age:
          - *k8s_key
  - path_regex: infrastructure/.*/secrets/.*\.enc\.yaml$
    key_groups:
      - age:
          - *k8s_key
