keys:
  - &k8s_key age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4  # ← k8s専用Age公開鍵に置き換え
creation_rules:
  - path_regex: apps/.*/secrets/.*\.enc\.yaml$
    key_groups:
      - age:
          - *k8s_key
