apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    tunnel: 3e4547d4-ffd3-4c18-803b-a71224b23bef
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: auth.shinbunbun.com
        service: http://authentik-server.authentik.svc.cluster.local:80
        originRequest:
          httpHostHeader: auth.shinbunbun.com
      - hostname: wg-lease.shinbunbun.com
        service: http://authentik-server.authentik.svc.cluster.local:80
        originRequest:
          httpHostHeader: wg-lease.shinbunbun.com
      - hostname: grafana.shinbunbun.com
        service: http://grafana.grafana.svc.cluster.local:80
        originRequest:
          httpHostHeader: grafana.shinbunbun.com
      - hostname: private-obsidian.shinbunbun.com
        service: http://obsidian-livesync.obsidian-livesync.svc.cluster.local:5984
        originRequest:
          httpHostHeader: private-obsidian.shinbunbun.com
      - hostname: opensearch.shinbunbun.com
        service: http://opensearch-dashboards.opensearch-dashboards.svc.cluster.local:5601
        originRequest:
          httpHostHeader: opensearch.shinbunbun.com
      - hostname: calendar-bot.shinbunbun.com
        service: http://google-calendar-bot.google-calendar-bot.svc.cluster.local:80
        originRequest:
          httpHostHeader: calendar-bot.shinbunbun.com
      - hostname: mixi2-bot.shinbunbun.com
        service: http://mixi2-shinbunbun-bot.mixi2-shinbunbun-bot.svc.cluster.local:80
        originRequest:
          httpHostHeader: mixi2-bot.shinbunbun.com
      - hostname: argocd.shinbunbun.com
        service: http://argocd-server.argocd.svc.cluster.local:80
        originRequest:
          httpHostHeader: argocd.shinbunbun.com
      - hostname: hubble.shinbunbun.com
        service: http://hubble-ui.kube-system.svc.cluster.local:80
        originRequest:
          httpHostHeader: hubble.shinbunbun.com
      - hostname: scanopy.shinbunbun.com
        service: http://scanopy-server.scanopy.svc.cluster.local:60072
        originRequest:
          httpHostHeader: scanopy.shinbunbun.com
      - service: http_status:404
