apiVersion: batch/v1
kind: CronJob
metadata:
  name: kaitabi
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: kaitabi
              image: ghcr.io/shinbunbun/kaitabi:latest
              envFrom:
                - secretRef:
                    name: kaitabi-secrets
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "25m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
          restartPolicy: Never
