apiVersion: v1
kind: Secret
metadata:
    name: terrakube-dex-oidc
type: Opaque
stringData:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:F+Z0RntaqDmiKlc4N/cKF1JgWFGezB2y+YL9LB9Mb0x04qGg+QGiRA==,iv:WaSRo6offwC2/dMlwW3JUa7bgUPr6LWBvXBHBOMhwCQ=,tag:i4YS2xAD0AVkGSw5zYxMLA==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:oPcrry7XgTx3AWN8r5mxQE1SuFkWREaSbjLtjhYPQmI05lbHQlEy2JLaFw4tY9YLx6XZfNYUHMEg1OHdMdWneg==,iv:cgPEhepmfPUorjiX3nhPITgHkk7vSy6j4t9S0l9Qutc=,tag:OWa97CXw/OEPUmbRww6YjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5djdxTFlwaUZiVHIrT01E
            VmpvdUdqZGpBSTRiejFscGhRc2JnRzZ6NGdNCmhyWXVCWEl5TWx5NUZqd1NVWXJr
            Si84Sk8vSm9adEs3SlpsbmdRbGxVYXMKLS0tIHh2MjFDZWphUGxtd2ZKL2NYYSs5
            WnVXbEhaT0hCYUFKRHY2c1RpTElyYmcKgmuIqjoKSgVJAUhvJ9LepUx0olsVtptI
            gVUXmRnOliPCgehqLbsuX6/6Uu4ypI1+Z+0AGf3YiMbBMNyzYXOIUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T00:49:34Z"
    mac: ENC[AES256_GCM,data:YRzig5X/3MOLwBJBSg9edSPRrOSecCW2hcVhZPa1Kw8ZvH5gbCSugBH+hTuE/3Y/1Lb/j4puJ5A5Uwr1ZHv9rsm8vfatmuleiqVih+N/nyP6QAHNa57rs8naqKlm+CKH7IDSRXfofdcNkQaLyUTvv7rwpaCMy9qlAjuU+kZ835w=,iv:OTUPYAW8SY8kPvg18h4GOyNaFUnwwzIQznBUwDEON1k=,tag:rC4KBgVtp3Yq/nFw8qM3qA==,type:str]
    version: 3.13.1
