apiVersion: v1
kind: Secret
metadata:
    name: terrakube-app-secrets
type: Opaque
stringData:
    PatSecret: ENC[AES256_GCM,data:hmWOhJGO0SMwv3ePhJ9uplXEXD/Q0lZ4qtaR1wo0mbujwtsMbw/b1AcO34o=,iv:tVrQa4PSOsW9pxb51e7yJBeCZYacQ2bFWcR2B6ze3Tw=,tag:/R9hTFj2S/dzjGKIM0VO5g==,type:str]
    InternalSecret: ENC[AES256_GCM,data:ANKwKVOURHLPzhTiNwJCG8+tnV1B88VcxzBseiWoFvw/FDi8U6jKmrcFblA=,iv:1n+ZYwF/0j67UNLA4enNHKF9NGJuOtckIxkCH6ocxGg=,tag:B46gOPNXptcsvBZM8h9exw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VUJJeXRtc01mZWswLzJO
            eDZ6bnRMdGhuVWtsVXd0TllvVmh0VjY0RUM0Cnl1eW9MMGJKeTdYTE5odGJERk1n
            QTZoRzJjOXVTOTVBNmxtaVlyZTAybTQKLS0tIHBFQTczNEZTMEQ5UU9QcWd6S2VD
            aEd0bmFQeEtaUDlINitGWGRCU1VhK3cK8sHHL16G/j7a93CEX8GIHSMM2D0dvu57
            c89ifUzgORZhbXhIVc1vKivf0g4pe/UPG6QaMU6UxM7cW5P8ldMsrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T00:12:25Z"
    mac: ENC[AES256_GCM,data:g/E3x7YUwL2CvSDB01QGtdxYjoQX/Ad+ZG5PpZQz52a9n6PS0m1s333DXDMHC0T4NbW7IiGyHjNeuQdWTz4Dhh1mlSwJvDTz4MklulOK+4iuwKEk21j0Epwq1NSVA4hs8bJsSpo2pQqOw+1TKFSvOL+yHrJbHTfD8TgLrazSB6c=,iv:IjbKdZ38O671NrM5BOrlt2I4nw1JZhsE6cTxiIpOOpw=,tag:4Z8+SRS2kD176i9yNA4wlA==,type:str]
    version: 3.13.1
