apiVersion: v1
kind: Secret
metadata:
    name: terrakube-db-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LwwbBG+XkPU8,iv:tRU3p+PgBq5JyAAsbE793EVmXGZ8G5OwzqbbBC1EsrA=,tag:Hep9eQjl0OdD5nbrOOoAMA==,type:str]
    password: ENC[AES256_GCM,data:DsoQZKprty9pyN4QZSsS1IIvvsfi9S6lPUuxDOmgguk=,iv:Szhj/fTe/KpI8zuIZz0blcj90rZPIzkrpg4nd1l8aJ4=,tag:AmgrkznO2Xnnp8bQpui2wQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldDdmcis0RnpCY3ZFQlda
            SUJ5eStJTjJlcFBXd2IrTE0xTDZ3QUNVazBvClFaakJvTGFKcDRuSUhZNmpLNXN0
            T2ZsbUV1ZHh1UTAxT2lPbWxZTGF1b1UKLS0tIDRVc3dhK3phNDRtVWdOMDIyRith
            WTBweFp2OVhWTUozN09Gb0V0N0ZvajAKuBSi/4M/vnOGvPvWoD2/1b2CS14KevIe
            pKpttP3LPHMMAqxIf1aeocgUnY+GBFeldVK3nTwR/B9GGRVGYdckfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-17T14:28:29Z"
    mac: ENC[AES256_GCM,data:pZt47SFQ/QSnu5YLRipYNdX3Jhm1VLKzFvLkQ1IiZx6DN5wqYWAMz41abmctdQ2diiyN35VEZgNi4U+gp9dN3JfqSSCBX/5eK+bhs+0LX4kNMLKF5+g8S8AGt/JfQxrP9Fz+S47A7fZPB2XjKyTyLowXhUohom/g0/0L+1R377s=,iv:V765kuwpZIPqhP3tN0iM2TWROYPtM6IHexLyNW7EKkY=,tag:h2HwliYAOyOA5O9xwLUV8Q==,type:str]
    version: 3.13.1
