apiVersion: ENC[AES256_GCM,data:HA8=,iv:mK8XE1P5vXgN45sGDgrFLEE67/hvrrEJxbYSbn8yoUg=,tag:x19tnnJSpuNY00IviNMaaQ==,type:str]
kind: ENC[AES256_GCM,data:jOiubRaN,iv:EJwe47bSJw1vjH8JtjmGGgWdss+jmZWX4ya9P2NcIFw=,tag:K1AiYqCmWc224k/TCg/OUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tyW/OiJH1so8KE35XdAFjpHxEeNmf/s=,iv:zGuTns3CPFy2f3UIjBzum5esmCukY5CtRMS90fIyPOs=,tag:xnZCcNrKg7KjH75STgCTxw==,type:str]
type: ENC[AES256_GCM,data:HzklnM1F,iv:Jq9pceyf3GkmwD+oKIlr4JU71natc3erX0ACjg+Mh7o=,tag:SzXH2F/JSXqBwbqgjxpp+g==,type:str]
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:E4rVIfaB08aPjh+iHcApGUH0OeL+oJXp7IvQCdHs0M31jZyX9yZ9j5XteurzNxbtigUITomXYrLOKDuUr5ff/DNEuNINHcIIcXVcQk34mUoyNqWzXStXHrQSLNiPE5kbBclAmardT5MkU9xVEGmvHTWvSkxJCZeeFA==,iv:AidyrZ0WCbKtYnO0lsnQ+g2a/LB9Wvxs44F0QoJUQho=,tag:uMYTL3N4p3rg8F+Na4yHWw==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNTd1cTBIdzNKaXM2ckhl
            TVo0Q3A3TTBsTnJ4M3pPNVVteGpOZ3NIdG1NCkdtSHlHTjhibVRNQWh6NkszRDkx
            OUpOV1lnZVppWXVSTVhYa2l6dHBPeFUKLS0tICs2MWZjRkVqdWFnVkdtcEhkMzZF
            ZkZPZW0rSnlQSm44YStnR2x0SU9IMzgK142D7fNtyPaMOJo1D+L4aF9Z+1NTMStl
            foiWIrVXRteV67F4nPqUEy1ynppQfxjDw+Xj9uf5z2+KCz9b3A+zQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T11:19:17Z"
    mac: ENC[AES256_GCM,data:U898fkT2d/dwUsV5isHAzn3uUGc0yirLlr3rTob+pc+ZvqWP5y+zGF1W3dW5lSObGntJ+pgq1P0w2P1khayFv1093fgeriDDTpRpqkPGYgRDTRZhw7LqQKUkUvwsC51Z64ER3OT0aS+GLjstp1QeoGKmgPlyItg0CdJM4PwixmM=,iv:f2//W37B2KL7yq/7x9w6HRxGK+0h8EYaNxockt2uG6s=,tag:dVZebsQpDkrXJqZ6+mGkWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.0
