apiVersion: v1
kind: Secret
metadata:
    name: storage-env-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:gXKJwYax8V8n4COZrL5EO3r8UNe64EZnXo2dXbe/UwKPRf2DzFenv8vf/+Rnj4Mj6zhBxpZz6TfY3nPRuwq1s/tWKzIcJIFQK35LWUJlQiYBCfMyvUK4pnwCCySaE4t/vBu81zLN+xBmrNhhY/E+KWiaJGDJ5kikhR6A88BF5AWwkDWSlwSmOKIxdgw=,iv:Q5x5Yzko7V3YBN42dqZ71y28rkr/wMF/42GkkKnmmUk=,tag:dXL7ludP/yfeTGBl0fU0iw==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTFpoeDlEWGJxcFdPRVlF
            cnZIWjJDRXdyT3QxaWc1aXZvVlVDMUhpNlhRCnlSTVZCNnhac3c0c0t0d2dCWUZq
            dXJjVGdlME1WQkltUFVEaE9zdU9pOFUKLS0tIEJoaUlDWkRSWmFEdEhkbCtjY2Vp
            UlFrNHpia0JaQVozcC9xeWZmNmttZm8KBqhObWw2wnK3vK3Y7Cq8eWlrjIOqHpgf
            BNg5EVm+Tdah9K6N84beCS33ume7ywNCndBcW5760nDpBLC1La9azw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T12:45:13Z"
    mac: ENC[AES256_GCM,data:pyZO1MHXPR5/RvcXMrSJLrEOQhAeV1crzJfg1yObxfRfoJUChQXLuNPlsgEHTf6SdAV4CNnUPO0lv3Wd73zQZz4n/XXciJYS2NwjAu7QZiq6MPQCuPH4fsOHUGD8nJE90Nx7JFMCkah38gaikwCRzmAW//lq5JJmzBr0OnJ5gTw=,iv:gvprEf64jaoYEaMhI5WDoVGITeVtbMFQXIVXT6Pve8c=,tag:Uf50lpXow8/DHSd/lTjlcA==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
