apiVersion: v1
kind: Secret
metadata:
    name: storage-env-configuration
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:ZckHRGruhW4chKCBeTIKWV5dFyLfMr73wBnOxtXAP4EDE5UO/YBbcimLMfBekNE4IqRHlLHjvkXgr1ji8uELPPoFhuquNTbJvWXEe3DNPJHV2w3HvVCO4uSlQYT7jVd+B7T+,iv:atdRl7zaNLcfp+S43143gJCNF41Qr7eJIAvQkFbIQAE=,tag:05chswqKpFQ7eLZYrGUcFg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTFpoeDlEWGJxcFdPRVlF
            cnZIWjJDRXdyT3QxaWc1aXZvVlVDMUhpNlhRCnlSTVZCNnhac3c0c0t0d2dCWUZq
            dXJjVGdlME1WQkltUFVEaE9zdU9pOFUKLS0tIEJoaUlDWkRSWmFEdEhkbCtjY2Vp
            UlFrNHpia0JaQVozcC9xeWZmNmttZm8KBqhObWw2wnK3vK3Y7Cq8eWlrjIOqHpgf
            BNg5EVm+Tdah9K6N84beCS33ume7ywNCndBcW5760nDpBLC1La9azw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T12:09:51Z"
    mac: ENC[AES256_GCM,data:SoqwH4/k/XlV4O7HWFOnzioeyCbFc2Vd+HQQDTQArUWpjBFxAQOOFNpuT59n/r9/1AlX0IL72A5tTPRuhvWei2OaHCtKuxYjGJ/McL0Y/l06XToCRyHc+KqrignazBSEGLw9BkkDsb3rMKlNDS3jIX37NG02KmYFvmdJEiZJE/0=,iv:r0d9tCwMP+XLRel5sL7k2DfZghIp67jkfLUmrTUgVJE=,tag:SnDmJ1XjKZj0KgVFODP2dQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
