apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:XwOtFZKNAOVO8iVglk/Ie53L2ulqOjKM2t4cxfw8Ze0=,iv:Ec0bTCIefoCbPGaTwcCgslpq6xrq16Ed/YBs6j7qXzc=,tag:riz40sdnKjMp31dMtgIiig==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:mz/VzORQ4xeEiC0OqpBSLx7T1g2u12av2+lYjhveuwGi8W6USW1TNewaBh2JaTIXhB+FA4xoTIxQvEfTRu0hhw==,iv:dvKd+yAj7gI7/HzOp5/z12go49NxGJ4D6OWHdl/xfbk=,tag:AmupWGP88rSissS+1MVhOw==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:OAyG8G8HeyMWUddgwXsAcqz/zsxuEOHvtb7vLraFE22kf52x4JTWJu2ESyVBAElrS5FjT1d8N79Dhu/qZNCLBQ==,iv:e1x209O5COxgc7n5easjD9JZsXbl2lGLUEN34QLoUkE=,tag:G/vo4QSqmv/i8ZV2/1v/7w==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OElnMEZiekxNc05tSVlS
            Qm9ZcisvWUxMOTl4THBkZ0RiOUorSUl1eG53CjllaW5iSVhWYlNUclFNaE1rK2dU
            Y1lheWhnODVRbVJSSDBkS1BhRW5CUkkKLS0tIGJEVHBNc3AwSnJJditqN3BHM0xi
            eG9zeWdCNFZUV29FQ2ZqVHZ3QWJpZW8Kvdp7W99DMhhcBbwX4db2Nz7SUJUYalL7
            cOlLyu50QDfRvGtUBNW2pdu9FFyK5l4QTcrlQl04roTrxyLfA/yWWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T14:18:33Z"
    mac: ENC[AES256_GCM,data:FZjnOZXnqW9aA+YWZ+vfDkN1r2zW/1+Dk6mZ2hvWnfZQztbegYdR3VoskIwbm0NFvLOOxYsBA5jVO7QYCPxepiEhyyajzGMinOGC0L9Lyk8IBBNHdgojHTrw5Tp0jjN0P3HPman6BRn4ehQEVwr3fURzr+A07biu0dl/+L0TiNE=,iv:FX9k/LUPtj3D5RW1/mBemiVoCY5kGuS7hylGhjJOLKA=,tag:38QgzXqM2ibEPQlYzkGoVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
