apiVersion: ENC[AES256_GCM,data:rrw=,iv:FsMc/xPSz0H17OwLG+tnWIEf8Pvh14L7r6uDZFgGCr0=,tag:eTFndyMJ5ZGWZg+balgv5g==,type:str]
kind: ENC[AES256_GCM,data:JM4x4tKz,iv:caPAB4tPyRBRIh/V4Pxv57zChbLl9i1N4D8V8cDrjNA=,tag:AYCrOBBQxxYAE0uMnQ7y0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/KihoI9DE1Asf2ICF7cimzA=,iv:YgpGlAjFHkDxQf24UrH2VbTIGhNSlKbgDkpBcN8NyT4=,tag:DYJ4XvuuAfAqxFo/69rhRQ==,type:str]
type: ENC[AES256_GCM,data:9O9TPxEo,iv:/MPZwl4eSdylK9FHf61v2hXHB+Xo3ilV0rIlau43nNk=,tag:XCBqrV4RqjvlkRCeTahFeg==,type:str]
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:OV27UOhLme6R84iuBEid6C7Nl0CnEPg97Eh+ZtNAFX8=,iv:K1fgcV/774J5poO6mWmSPfPyNxX+alyjFLwKyfmplUU=,tag:LU/inFsY327t0+FdPfQLUw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:JbFmO6kOCxiyJKdU6btbTiWg6WfZA8fFyKjXrzDn8/6bpu8xkkdKi+sGMKmQnWxX2mPa4nP4Xj1VqKL2xGycLg==,iv:8rPX/4kYhI4Imm0CaOV3m6OvEyghp8a8kKd/i+K94g4=,tag:P2IPfZxbl/tN+LLDoVYUZw==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:4wJb5RBIp6c0OoEK9W7zkEVYOUqRegNEAFyx2jFVHBmEgGgTJfEUHfxL70hhk8qoIAwbaUqOoFgibp+M5UScIQ==,iv:qYUMEk+5FPcZAZTZfqiZWbvCnMtzdv7KaC8c2ZFndlg=,tag:H4q9G+2KzBytU2ZTN4LePQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTmpEclBTVlFXZDlrM0xM
            TXZwenJPaVQydkt5c200THpZZnpjakVTWkVzCmQrSlNzVFZKOHV0OUErZXRaeGFq
            eVpucXVJMHhpQkpGSHZ2MjNTOW5oNlkKLS0tIEl1T2VqL0JId2lkdHp6QUxIZzl1
            UGIvVjQ0a0ZyYkNBT3lhUzNVYkw5dDAKZiA9+3BXzWjcpluAQqQ0h8uPVcXzJkwT
            S/i00heioZXabssQSnPsNYcFZn0n2HhDxiylABhtp6mclQMYaC42cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T14:04:11Z"
    mac: ENC[AES256_GCM,data:2fyz9ilolM0D7QRprDveI9x5OgBcucuzY5Okrh/eqV7jl6nqIGHiWEAOqNHMqW+mt2leMja0vaan7o1hjldL2ScRkg2e50Ui15s3rIROuH1XKRc//3nGgV6PCr/mao5ULx90S2T/ijSeaRGzW147uXCRAxkVZxXbpo4bBkjSl4s=,iv:ryOzW/LRGGq43J0EQe74/xMTanbEGba6b4V1vJhq/vo=,tag:0M677btWULlYmDy2hX0Npw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
