# Piraeus StorageClass
#
# DRBD レプリカ数 3 で PVC の HA を実現する。
# LVM thin pool 上にボリュームを作成し、WaitForFirstConsumer で
# Pod がスケジュールされたノードにボリュームをバインドする。
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-storage
provisioner: linstor.csi.linbit.com
parameters:
  linstor.csi.linbit.com/storagePool: thinpool
  linstor.csi.linbit.com/placementCount: "3"
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
