apiVersion: ENC[AES256_GCM,data:5SA=,iv:5HkrTfGKCOySXjmZdAQ16w4/GDQWmt7nuL9+N/hDgfE=,tag:FOVGjZmeBfGxoA9ZCnmZ2A==,type:str]
kind: ENC[AES256_GCM,data:ZMIyNMvW,iv:+FD3ji65ZbA5VgkAW/z5snHmWMVYLQJJjiaN8qcYjZc=,tag:lOwDkGUPt06is6TwwVj4Lg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ObaNX/GlDcgzRW8wVUxE4n65jj0=,iv:Lh8KfSr7WlvLUEQYKirFzVSLPobK1MD7qcKAXfdB1W8=,tag:YKILlw6+PZyJ3EJzV897Cg==,type:str]
type: ENC[AES256_GCM,data:V7hqmelN,iv:KYF+rAkOitXYH1PARJ+I3GD2x/IrLu10L+va1OJjFZY=,tag:lSBHixrL5QbTO4XJdsHBkw==,type:str]
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:++jwfZSSQBPDMpPr7EI4hzptudkEju+sdy7CoRV9qYQ6X53WSSK71uOWlU2KYmvYhGdu7bBD2BAm6ebRhfclnFQPwPLIwYYUH2D4rVeYnilEYRw68yCSEoFIu6DN2F+KQVWlM/VO9u6ZK2yEWO0fcYNjQTzCC9EsAA==,iv:tz9ZvyEfs04uVS6LTNN/oSCaRFZ2rp6xcic14x/kH6E=,tag:U/VoxwJkw5ytLTToTwXKRA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R2ZjbFNNRllMcDhmSzlv
            SjdJYUU3K3JiSDEvTVh5d2pzbkc3WEN1UzBFCkRXR1hvVUliWEFPdFlsNjdZaW0w
            OGJpdTJhRG5XdnkySTM1MStXc1FZZ0UKLS0tIDdRZ1oxRkRmRG9PbWpKUWRaWUJE
            T0I1c1FrSGpaWFZENGJWanN2VVdza3cKUBsLe9p6vqH0S8VyNOHuwIyVloovlU/7
            Q0CiQUhyThf7ZOZLJeZjAof/hKyO/RgdmPyTCKKi+7n2TtAfknOtKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T13:57:50Z"
    mac: ENC[AES256_GCM,data:KWo22+3LK59Z9ljezD5/Fnjwu97p8X2Re2qO2GTZE7E4Pdb1MmrCacM1XGr1j7phH7mRJeGt0cNg5hGU7Fu+Gg62Uxl0piXu5AeA22iElbH/LNKiTPNCCfVAKRPG0tbYcDzyFxTiJMob5fYEUN6/1he2wmTgNKMkCynd2Cg/BV8=,iv:cBC7h248LdlGyKsQu6xqcaHH++llUqmtN/rtXT84584=,tag:VfPEZW/iKctDiu5cEbjcng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
