apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:0B2e4/ZUrVLvxVV0DGZ0wc7KT489ZSnRf80B/i0DjMqdxzxctMrNLZsryj5LuXQ9BSOytcMXPJ0jLJxAwNZP7MeSOs1QqgBCIkmLXp65f/fRt1Tp5QbZnhw930QIGwPrBMVz3jVNQ2wmfUiFeUr5LjvfqWVmxaPl3A==,iv:yfTTL9p6CWig5mAlH2+ZVYSO4RTDaZ7tcluZJ3+d5Hw=,tag:999UzOqtoahuFpY9EuOVPw==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTkszL2hOS29ESityWWR2
            c0pBZGZ6RjZXVEdDVldudWpxNW9icTJ4UTFVCkYzemtocWdiVTBOQmgrSjZnUkpV
            M3c3a1BiWVVPRW9DTGpBMEU0TjAvRzAKLS0tIGtMYXBkcmxJMW1rUmxLWjhJSVU0
            UlFCVklQUVovUHI3Mmpzc1VwK09DTWsKvde7gbG3S0+f2Dhj36CpTwF7VCF9xar4
            pP0IS0KL7blRw35Z8WnFsCXbb/8zKPynuErAG8e7lKCNiGREgqlxWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:54:54Z"
    mac: ENC[AES256_GCM,data:mwiOlWalLqiNG6MXFqminVKbu4XwSFEYNO7tN5tL0f21dMbpf2ytBDUFGW1LlrYMJ/WG/OvjgmZO6qm0E7onSJVMkGcR7FLhKkG+ByfFhPaLVktG5QZEHjXkkpIoLI3mwcwMVmvb2GuHi59z+Y5X12fnp4TxcDXJNmg7SFXaMF0=,iv:N6VSOBkTjk7G8vnuOf3DcaOUnAeiJs2tt0fNiyUmMGw=,tag:FByxjMwQIaH0ZS03FsAmGA==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
