apiVersion: ENC[AES256_GCM,data:y8c=,iv:BPrsTInSiD4OT+VTVDD1wmVhKkVoxmU//qGUk3EIZmI=,tag:pOjO9BXyThPwbxwvD/8sHA==,type:str]
kind: ENC[AES256_GCM,data:cT9q0vUH,iv:Vy3bp8uGUf+4S0K+dJ7h3ufZu6mkssDpiqq08J+xyR8=,tag:Q89q9iGVW3WjczOstKE5dA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:V4avwS9/QeY2PBe9xp1EIJAIXA==,iv:Iu9lRpYJqtgzo0LcbiCB/zCN9Vas+RDxSvKzDQezkQY=,tag:3FJ0iL9w2tQt/qZO0Mcf/Q==,type:str]
type: ENC[AES256_GCM,data:Hmam3HxK,iv:q7zJLlTX3usDoxr/VBlnclksbXAtkpJIn9li2wpkbw4=,tag:8MLV4C7TzEYaRh7Jbm+bRA==,type:str]
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:PwG9uJzJUxvJUfEYIzevPaQlyGbwOTJofl5q3b0q/y/UO1lEUO3n2lWPGrXnViX9R6tk0uS8WIV5WlaCALHoohCYeEor/LnrSkVeCb2dxZtyr2mlaXbC17vJy6ggwuWTYNdEjeTHv5H7MTfghlsaKUY+G+jJx8HCjC2F1I4bWsBhb/vGPoyVUgWwM7Ms98g8o2cC3RoNRO/vijmMPQCKmd8ZdyxusH/6lZmPuT1nTrvtNLvIeo8zmmLOJuYLkpSLZGBpwrzahZIOncKP9s4mZ27sHeUfmEULe9qurYvjZ5/l9zuwoGjazQwF2nL8eSw03AcE0d4s49k5hC7K2FsiW/bbJv1axZe2MMaGa1G4L78sN+k3BJO87lUoHY8pGahA4Eq4+7mEfFwOwxHiwVPH/UzPWNqiaWrE7Pzxhp3l6wOovV1SwUuHfpWR04pocGKBNta1JqyN55d1j6mXw95ZTxSM8VZ4+foTQaXY+y2J8ZR2qn5NUrfYaDHxb+MugJnAnvZzCwtIRV2ijjzjVvI/vl/7+BZeICUG6ocCR2v+YqJBB6Mw7EAG8A++93XmCr8jjM5jFC8HOKrBP60p+tGY7Rq4J+74xFGssdMIr2ysTJo/UABBr350kI4uPtdTZCNXobraY/GA0thGc8UfglNlGQGNCU3e0BcoRx38zbtKl41GbyAezxI50YF3t7olL4BWqfXdJmgbu7fYZmtXoa0b0BywytL93tBpIqRs/gHTRM5kQsc1S/iDz48tl08Uz0b9a4mKBB7hq0X0RlJJXx7NfzltePlWDYKm5Q0qqDVKKwty95BZLvnT39vWgoBV2cZe8/393VoDR2nACkLhW3SsCvHBppiIcfoyd/C7o6FDx6p41LeLhcadxxLYNTkqwMvO0BSGmB2LJUMWR9N9IP4mbZDOizN3V9d/wAwqKqx0JrmloVZ/y60+MhP/FKdFujc1x3RuhQg67mzM4lk0gnw7,iv:jnV8xwp7ivr/cEwGiRvD/0QhP//mrUPnW1zCAZEVQZI=,tag:GPFCwGUc+AH/jvMj0DTPyg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UWJveFdLcVlzYnR2ZlFk
            UWlXU3pkcHljU1pCTlNSV0hsYXFRVDBlclJNCmtTZkp2WnlCMkExWGlyQVg4MUxt
            ZTM5em40SzV6eEdCa0VlRkNlR3J0Z0kKLS0tIEExYUhjS0JCK3pCMnhmaGtteE5v
            Q2RtNi9lRWdDT2pMZm4wM1Q4WHkwVTAKm5lSUoSwFGO/SbbPZY8opXkXm3G4IVpq
            DBCA5lofVC1gwt0Bv65hyE97B/ScXtJfhMK5pNmxIIZJMO3dNR8S1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:43:30Z"
    mac: ENC[AES256_GCM,data:Dz0Z0av3pgPecHFeDk7lD7IuV1/q64vbDWps4KJRuvAbpD/SUnvB13vA4jul99+Qeu4vndNiJkO7dggnBAr9O4i7L1pho384XLo/q+kweDOqzWYwiT6VE6mfuIhYTp566poYC7KHwE+gWnX+Cofcf6JDHUqLAa9jsZBhEE1K8CI=,iv:MWQUWN2L+jzqGDeIjvhmSqKiQ14I6QjMY5vzDC5Uuvs=,tag:KL0ipJaSN23KIPpVRkBDTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
