apiVersion: v1
kind: Secret
metadata:
    name: ha-prometheus-token
    namespace: victoriametrics
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:XT3dHXqb9uKP4GxEvLnAE8dRw2a4vmKunUx6ju42Z7Al,iv:qLV38cF1oJ67K6ASshUM4sMKoZ/IUtCYAq9iTYw7gBA=,tag:yNBjlkd/+mPPVa8AcxpNQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUWVsd2dFUjloNjRqOUw2
            UUJwUi9DbGZibDBWM3lpZzY1WUhKci9KTGtFCjhwSi9XWk8vbGtVdEliK1dWMCt4
            dTlVaHlkSkNMcC9zTzIrUW9mWHhxOGsKLS0tIEhMUzFad2d0Z1h4VTAwK3ZjVGRl
            RGFMcllzanFOekdvVWlJcUlyUTYyckkKVJ3S1UkCfcZQFr6SkasjOz3ptktgEmTm
            twS6VWXegLbZ5quVQp9FOOPOzXc4Q0blOy4LYpsGvKOwUYl55ynwqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-30T03:08:22Z"
    mac: ENC[AES256_GCM,data:Fd/zCrssGdf+tqyhShzW2Wc5Rtf/sRwsPNZQIVZXWs3kKpZ7qysjMZ9+kDtcnKGOvx34h5iJxBAaWDGyG2qwi0Xp4TLSz7Ff+BLTX6zOWgVDN7EwwuN4yS1tQn/LxjNFMEdQFI/1V0hcxOUDzz/H7FEQne5z6nR36Wjzuz/NK4E=,iv:CnDGtLOSyllChDb5xpagiM6Oqp6fSq11soomeAA3AoE=,tag:xof3aa1/BAAjDYJPID+kXg==,type:str]
    version: 3.13.1
