apiVersion: v1
kind: Secret
metadata:
    name: ha-prometheus-token
    namespace: victoriametrics
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:U2T72Ngh0YLJhj9ZIhsnwinmUgcrsfNDVB40FVaW/18fA8On/JKDNjjKEuSWsHVWLsSb6yaek04S1w17LpoyZi0SboI31D40QN3Y3zVGCRNU5cP3Zvj9hRcu/X5RtX70577imOYtx6OaVBAlrJG4gezNfBFTU4S0VmGmjEWhfOSXU5p5TPkG8CZ46QIaQZdJXTC/zDcO6GrKpDt5T4bNzn8Ukb3lOKBOewJS0AvBGtAxfouNSTeJ,iv:W/y0QvfxOIcOy57o86+zi+0GjJBlLOyeM2aqc5h8J/E=,tag:kqyQIexsuzjPQT1cNKNabA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjdoVlFBODI1aFVsUzha
            YmpCdmdVSXppRXRzbGhEMVhmd2dMVEJ4UFFNCjdyNjREUi9zd2UzQXFJOGdndU5E
            b0Q5YnpzaUd1djJGSDFJTlM4d0xqVW8KLS0tIGtwdmtkenJoWXpTOXFiUDVia0pn
            RFZibTVER1Z1TktaMUJ5QzljVHRKNXcK4GNBsm7iwA09sWskAjKCP+9N8MVQAFW7
            1hETm2/twWESdWfQ4RSAAecXFzF9wk2m4rtRsyeBWKObq/eYHoUg0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-30T04:41:51Z"
    mac: ENC[AES256_GCM,data:JGAL9rrPDd+ftaQo/NKY2otzT1j4eBuYQktgBRf6ZtN2jwdnSh7ItoSmVus3ZDzaHMeUyzUk1IG6RcjmfsP52Xj0oVKpyyk7xpeVS3hHJ7/FYWm0IzJB8rtUUEXqRFDBRwbhRkkm9VffCjkPCB/LMAPfwWwZ7IAqfPKO584hubY=,iv:6hO5LQKXEFF80eJsdhomPu0YgQGh0HyXIQlV6n134vM=,tag:rj6EJsjchJJDcQeQC6WBIg==,type:str]
    version: 3.13.1
