apiVersion: v1
kind: Secret
metadata:
    name: vm-monitoring-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:LIQAeyjGlBmqD4m1mNPDBLJFP2iw99Wo9dOlqP7tygMV13vBmrTI1yptR/Ibb42uounqLvOGqqcL3U1MU/SPmMTBIl0aNjHZBVpZWi0XxRrCCzObrkIkmhdHmdRvww8WBM01gPP+fIQWzSIuDwWdp7qAUP4n+4KLMVjg6aqLYLOxK5tk1HiWfXnk/8OMeti7kXI5DP8/Eznwlwq/bPG4ICGroLIF4wcbUC/kgOFpUOB2RGAJnY5XLnBYMvelWnVmiTpoIQPImhPxwhrjCJNO1jY+O3iFkjdTdHZfgcy298ke1l1haRldPoNDvVUaYyAY51Noa5wN1xeTaUCMEoaEoZAO+Bh/ZI9jOY4vMCn17IU7CO+xYhVCypJBabyhUbI3THdJWCvPKvgiqGvPLKrgQ0RqbPZbQqfTHfzwjHsXh8hqitNDISTFVS5CUENeY1CHBTNBrnrfsGGPyV+Hyc3Cv00hvCmPmVCQwztVEmyu/Gb3ibYDx2VO0RjcCqkiLbxqR2bh8K5uDSvxWYPT27G8GD7pjKzf61zW6TOUVyhXytRqrN9OTIuY5KmirzVOxR4+91yvl17ZnVc7FK7Ole+I5NmT/gacR0aKEJPbpkpoUrk4tXRMQ3lZ4nllHU2OiTbUGGY81UUTJk6xV78FSpwwOzAEZ4TU6m7VGayCavMXiqSoevB4lXNH3mBNm+Y8vwmsGoWO7Nek+oPxCn06Y6cQUWXrD9ySHx+p2LlYYmgjUeQPuz81EgDk1So+8W6odIrWsdBmk3Mamsxn+XT7F/tja2QVv+Nsl2L8Mxe1/rCDmcHekpB8lEY8k7uy0m77yYm+IKWwPTH/O5crTpuegCiYk66bQBczZQ9sTJs5giH3oS26/IF/OtSYCW3H74ixNm0TV9gMhLJhSFwaKnYAaFmH47+bsDnnbbZyDuNGJVqNz2707UxlJwQLiqbW4im6eCkH+bX36XgIMpGjP/QMrufi3VpKLIQdOKHnKag0YGVQbcR9UmxsCfIl3iSBGNx/TPc1HsehuMBfC0Z/3GVfz63zd6JB2AEXJ6/M/XUNpktKtgufBvJzC5TO+kZGC4Z12PNPNH2TaMJ83Ar47NSQMVs9VEMrSLHc7ec5G6pio3elTJkrUSJnIgu8BpA3SU/F0Qb4b8RZip4Mh7ObDBmmI8KtjyGdV5z1UGy1UcwyedxVmduJhfRC1IIxgeq8oKFi7wPoO5LI2/3wAoZ19T8w,iv:vBovnmN/iHh0Qroq/vBY34ehcykdg4tMKyDhKplrQVk=,tag:hjk7VyloxJ7MpfvkiyZhkA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNHhxdVI1Vko0TWFXbWlj
            WmlnSjNreUdGRldVdEpQd2hRQnc1aDVDOVIwCkxEWkZlTTkzZVNiTDhNNExQK1lF
            LzNyUENHZEVXeDFlVmhPWnpBVHhxaTAKLS0tIGphalByeWU1MEpJN0NZMnZjYVdU
            RFBoOUx0Q2d6N21TYXN1ajltUzgxdW8Ksovq3GBl4vf1PAmz8gJ28eRdbYzPEKYT
            fgWOrgeM35sKlq3WsJblxvM2rtqRN6JzHSxrJw4R9yr2mT1D+cIi9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T15:55:50Z"
    mac: ENC[AES256_GCM,data:/H87GZLflXH5fN8+RZyKBVy5o2ifWzgbMQ9jwJjDMxC44SQsKtWHwi3r3mQgr5ZVo0Td2yfiJUSai04gyUSUO9EeYOhJjufnfiV3WDd2V4epLfJkqJvubrJrWPOReqr/01GteXHiQgfT25Oxo2xC+v8K7JPdwWFYXtQBGSsyqs4=,iv:km3JthMsl3viUSjnQtNr+l8nA+vULojtZJo7E3zz9ok=,tag:GZP9+pOn/k/I+Q5hPJHWsQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
