# ApplicationSet: apps/ ディレクトリ自動検出
#
# apps/ 配下のサブディレクトリを自動検出し、
# 各ディレクトリに対応する ArgoCD Application を自動生成する。
# _templates/ ディレクトリは除外される。
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: git@github.com:shinbunbun/k8s-apps.git
        revision: main
        directories:
          - path: apps/*
          - path: apps/_templates
            exclude: true
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: user-apps
      source:
        repoURL: git@github.com:shinbunbun/k8s-apps.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
