apiVersion: v1
kind: Secret
metadata:
    name: mongo-root
type: Opaque
stringData:
    MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:80BCxg==,iv:sXXD8v+UR7XJv+2xU93oiwxNX8vVDwjR2UcfSsyHDi8=,tag:jh/HLjwBQYIoRKSJDwVf/A==,type:str]
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:Ztd7VdUCNVqjfJyP4o8tp7jOmJ/IOZdncaPgboPMwN4jD+ud3geI2Q==,iv:qF0sNdD+RVKprcCKREgzpPBAGl7sIYW2qqT4ShnGid0=,tag:ofqQ4pIbU/tUjUObp9/ImQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK1BKSjBLaUV5K0VxTW1z
            K2lsWEkvYW5md2lOQlVzN0U0ZzZRb2p0QVFZCjNRQTJTNW5XcHNGOUdCYS9HRUNn
            SmN4TEVpck5FbzJVQ05sRExuS1RzdWMKLS0tIGFIS0NVbm1jeUlpZm9uTWNxNXVx
            ZkxXK05IQ0c5aFh3VFE4RHFZZy9nSVUK4iPpoDAWdBsdKGT2iHS9mKHyLYrVVtb6
            CIowYH9GuPnqjphkJNJPSTjlFWl1oifd/lkfT1YB5YDLKAy9pF51tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T09:23:26Z"
    mac: ENC[AES256_GCM,data:LvbGntFQSuozpYkC5Lzq8Z3KT6eAHjGE/hDPADjaq9Vh12BwC3UAE18Tov91iTgf2B+5Qa0A2MlS+y8ZSPWMzFqJLQHXcNgKc+6C9B44FWivGEIPPi1o5K7Ly8qZfE7XCnWVbJDgfX/hNE4PC7hEeGrJWZdxVICpTAV1c41YHQQ=,iv:i7G9UiZpw4JoLTozSW9PERngajlcWytxeKleobTIZ6c=,tag:fDq1y/SGBKsipr/ba8BJqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
