apiVersion: v1
kind: Secret
metadata:
    name: mktxp-credentials
type: Opaque
stringData:
    credentials.yaml: ENC[AES256_GCM,data:ngYiJHv6PCw8xmEus+NODFOk7SW4G7YCz6FRaxpn05/sqvJBYzBNw2xbpkro37tyFgkiX/I/gn2jkUU=,iv:Xm4g4y5IrPmpPn9MQia1i+gXKalDxvO4ZHKJJfmrfGI=,tag:aytGGue7gRIkqGBth6PAeQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTnlvV1N0SnpTWENvYVBN
            RytZeE1UUEw0UTJFMGVMM2ovL3lNdE9ycUdvCkhnejlnOURZUUhKeEFkSjJBeVFQ
            SG1aMXd2N3k4SDNVdmJtMVd4em5WVTgKLS0tIGFxRnc3U21qTTB1N1JsTmF6M20y
            SFdMZjdPTk5IV011bzVPK2x6MGFiVk0KzKw5PTUngbSfmmXeZlRhrFcbq+KX1o1Z
            MftdEmDq8xl2qc3yBY6CEmGR7nscaPCVtNRi1k49gNZkJK9H3WGBqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T05:25:49Z"
    mac: ENC[AES256_GCM,data:vMFqozjrFJ3gdHq19GjD7bWGyJMTMbwz1mf0jr7tj5nIKQcAm0SjXN49ZPsBPdV3F0i+JDq1YqzBnOzclpwYE80SBPgzKmHSsaAmwdfuMixz+GqaDDnaXIcCvvNMPuhWsMQjU+i291Oi47KOrDYitoxR1nK83nate/h7oJPv6HY=,iv:87A2QhakrAh6YUALxxJ4hB7usRDQe5asZUl7DS1MI2M=,tag:DtziNzen9BX1BD617J/CBw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
