apiVersion: ENC[AES256_GCM,data:wl4=,iv:An+g+PHoRIcarZLrPqKt6/9TmALAlWMRmlOrDSWLPEI=,tag:PhC0E2sFSzAQNY08sHFgYA==,type:str]
kind: ENC[AES256_GCM,data:AB6JRtVW,iv:2n4wx7Ey+vAmoZpHmy2lEfQtjgCuoFSPgI2rDjVjddE=,tag:Eg78JPwC1sv2T4++UIV7Ow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:18Kz/mAnUX2nWofSrwOMtBHMU51KFQ==,iv:ohMVw8UQOnmbS7gG5JVU63nmxkMxzl2/+fmTPxXfD7I=,tag:QXJNbqEr7Y3nwruJ77UqMA==,type:str]
type: ENC[AES256_GCM,data:GN8g7a6G,iv:LWl+MEe8lWqJgYiPNAspCzkySpixWv4mQykjiKSuBJs=,tag:RN0FPD5U+3VkkMfBgrfuqw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wpreuhguJxq2VF0=,iv:u9rlHCNOO7kKggSUykUoHp0d/IFMMiJQWbsTsrWDja4=,tag:6sGwy149xuh9kwSriqfHFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x9nWQ+R9Bbu6FYmhYAUBsXbFpiKv91R1QxR72qlSZvE=,iv:eux3nACCHG30bw6mvYr/S3CA9erNmvL6E4C2RrkITfc=,tag:YNpU/10+NGuOSIOu3bd1RQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dmplWFF3UlRlaFdjQ3dK
            eThVYjBLdlg0YUlBMVZYSnk1MmdQMXc3andrCkVxemkzNUlPUnFaUTNEd3l2RVFj
            TzU2V1IxK3hoZFZ6b2pJQUk5Z0UrWEkKLS0tIFluV0ptOUVWQzZLZWdxUzdwb0Zl
            MWtLUklUK3NQYjh4dHN6bENHdlV6U3cKvLK1k4tx39vKyZN2SZUF5RbkG3D/HUbF
            rYBdQFeRYLOwBsZjX9r5exr0yZoiRfmdpmG7TBev7xg1mkX2KFpPWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T03:59:35Z"
    mac: ENC[AES256_GCM,data:ABCb03OHutw8DOQq7lFq7qlAoxUqL1m8yskaMzPwvZTrRV3S+O8fxvrzQAgofEMzb86YLQMhgE8hvmFv0b4Pt/0rYcg1YEhFEG9t31Wb7DwQwNQbVNZKn0mj2zDhC8z5POBYIGaRashgmLB7Ifu+KtR2quYrmGSE68aP63TQvxo=,iv:0CWB+NWz0aDnOykbZAWxInnE8K0E2lARgZMMm+UImT4=,tag:QaGdKRO/7nvO5Plgxi42fA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
