apiVersion: v1
kind: Secret
metadata:
    name: grafana-db-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CxoflFtyrw==,iv:jpdL0ll/+PJCSALdz5uNBUsBwy/SSOMt3ceZe2x0l1E=,tag:32YXXH6i/Wl7lH2G7OLPdw==,type:str]
    password: ENC[AES256_GCM,data:LjY5P/Osu+Lep639jg3fws3FKYnVZWeRdKod1qTbzm4aXnl6+aOZDA==,iv:7gi/RTWu2Hp6ALwf+qyTVK1/mYVVgEPfzkF7ntOEzxw=,tag:rlYgpboaUUGGgb3oBUEwCg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdmZuRGFTV3lkcy9GNlRM
            TEcrQk5uN2V5NWg0cFB5V3BPYTkydkRseDNRCkVEb1o5RXR0UjQ0RkRjZ2lMVUha
            OGYrQ1VmWnQ4M3dyTUVTSGFveGpURmMKLS0tIDdOMjZuRS82MEt0UjIzUUVqa2VX
            YnFLcUdtRXozcjI3bHR1TkZ0Q1FHY2sK4p6QerAumkApu2m0xnJuei4UcoTesxVN
            e0YxBZUtao69GbJj71Czwzbp9Ijv4e4I+w4/ZIFdVDipOK3iWWdSbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T09:13:54Z"
    mac: ENC[AES256_GCM,data:VQTYoZZvhBhPfl87HQ6yoRhjH2hEdzhCpBsTMIQ4fmUchGG0QHuz/TiPgdberywyCM2lAWMNSf4k9oaMfDkxW92D4aHc/UeBfpGclRG2lT0cPPIsNQWuWEl0CAh3Tplwg1g01V+dr7fNPn5/m3E1M+569p/V2ZyerhfXAoXJuds=,iv:7Bm4TGyMkolUStVpHK2MKTH/dTw7OTdNTOpV2n6vqqU=,tag:x2/puDN7QSwC/N/iEhN4gQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
