apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
type: Opaque
stringData:
    GF_DATABASE_USER: ENC[AES256_GCM,data:yGUGxCO/hg==,iv:kfAr5P9GLcpZwpE7aCsA7l1e+LIx4xYP5ugl0E8OoRA=,tag:oD1bZmhdIQJvn139Ku98AQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:cDiURbKBfn0xjHnFaJKUJUEWaV6/Zt6SZ7pLa/t873M51bG1TBxomw==,iv:LzQ1GK8u1R89e+z700aRRDM7unQZAi46npCSWmxlQdg=,tag:EjVumM7vZCaBLfXs4a0WWw==,type:str]
    GF_SECURITY_SECRET_KEY: ENC[AES256_GCM,data:5GeuZH8vRp1l/p7JNbtIdBdJSB8KMbGnnYConIay31js0d04CISkOaJO/thKml+Obm7pT3KviAGTU8ncgvWMCw==,iv:38UJn/80/uKor4FVivD5eirthyWBPocs6hkk9rKuKuw=,tag:3JvRLCF+/eDAtibzcvihGw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:eYeYGBTS8f6p280mfLkMKP1eicnpU077GDuXTMKvB1E5WkYXQfnCWg==,iv:Kj8V3GS0m6PKtd4RnW4OqXnuJEjIus3CvyHdxBKZyX8=,tag:/mtT5WuH7kpidwzMi/1bVg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wnPNQae59LoJlLCJDEZGYrz+CZNXAFAMjW6eb4GYTVhf7uFFsH0mbaZrXhA1qNdBaFZ3uNu9JY6JpuFwUxIJlXvUvZwSlnLBVwoiVlp0i3WyJVARzOxAOyMC5sQH8Mjv3tCyOsK5CkMrYjFdVkFK8PKSftfAyHNdiEwQVusFT1s=,iv:t7O0RSE3P1jBlqaox+51DhlKBPHO7R4nLnpzg0+LxIw=,tag:R4yYehszCZ3Z3HlfUrYEXg==,type:str]
    admin-user: ENC[AES256_GCM,data:PCs9peE=,iv:NRtE/rpog6GGzrhYoVxieRA/J0kBCWJUeLbIXP2HeiU=,tag:yG3OkHCXXio4lcgQ1sAQSw==,type:str]
    admin-password: ENC[AES256_GCM,data:D4ARsiFAtsEW85WSPVs8Ae0bR/0ZmwHUT8i9JIhDTzE/0Uvcn9t+yQ==,iv:A+r9QcJbiGf6Wc+g3b19gxV73dznlmee2Z+hsvHClHk=,tag:iShxkt56nGucgYYhUAZYnQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OTg5QUFnUlV3YUI5Tkkw
            YzRoeVhKR21iR09leXJYOHMvbmRQSzVYaGlVCmMrc3cvYWhDL0tTK25EM0xWaVhl
            cm56VzRMU1J5R1VqTFJyWHMydGlwM0UKLS0tIDdVcFhJRlVNWkdPMzRad2lSWGNm
            bVZmQXl1bXp5cVNRNkgxcjB2ZU5QVEkKLpUOk6e5INDa/7PdjNtAMLLSHu4/oaZQ
            uJyAsrR19RmpNuLk+8ONBtdGxQusVW8XkQF/kbqjyXx6aB12qjBjmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T09:13:54Z"
    mac: ENC[AES256_GCM,data:a7xv2hQlm9JoKw0LTahDBOTbsGRO8XAqYhycepBdge0022CtsTnqtrJ2X+Mq9gY4z09NRl/GETowdtYzwm0wYlfn3LSf8FAD+b19374ycVwvHzq+bTG5au1qE5xu4hoKlxm19YdiLg4+cu8zdQyEYSpKck5/toxLgvjfGOnUf4k=,iv:i6cetmh+HIF64+Ff7WwxwsqQulok0rg7/2yqsIuKdGE=,tag:pqOguZkkdYjYb0nYR09bnw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
