apiVersion: v1
kind: Secret
metadata:
    name: myduck-grafana-password
type: Opaque
stringData:
    MYDUCK_PASSWORD: ENC[AES256_GCM,data:NmTbELJkD/fLOEGZ9llr8dnWMhScu6bVzBk6iDnVFaw=,iv:/sF/FoUIbcDw8J6v+uzrODYI5in8TqP8vn1naZhPFZQ=,tag:NcuxwtW+xhO7V51jJ921Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT2l1L1JzOHMxTnFwSHhT
            TXRFNlB1UFFiV2s0eVZhTDY4OEJWMHlWMFJVCjgxOXcwWnh4UzRlUDJuVnYyTjJY
            VzNRV2NUM2V0T0lBUklwZ09xQTR6WjAKLS0tICtBRUd1c2tVc3lNU2hoUkZvekFF
            bGZRZUEvVGZLWFU2RzhYOXJDSkVLc00KKtjXlgfMXMpVjFNFORW2fHKFoLZ2HQDA
            NM3W/8WbDuXO4I6g5NS9gkUT+YZ3ls9utN3JEHLjclk5ps2uJGRFQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-05-27T15:36:12Z"
    mac: ENC[AES256_GCM,data:ZUYQxiZCBB6VsLmcGORUCcBqBc1eYXvbhnJLuBf8ZC5CsxpEs4fu56cYzSqAQGcxPUVmi67+XrvwJCEZqO6HcKn4E+zEQ6EC81KNy3hAF+oDwjpw/hzSoUvUGIgYHd4pAkU5fnvQ0/WZ4TEx+zxTFHNbc7NX8pZ5/yFSb1/IGlM=,iv:ZOcU1xuedPGH9w74Dtd9OzVJKLq0L6hY62Uss2+3eS8=,tag:sXvmjyhu4G1hZHuSPHJiJg==,type:str]
    version: 3.13.0
