apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: peer-issuer-data
spec:
  storageClassName: piraeus-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
