apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:OlSb0RF5UuOTo9j25XH9E+aJgmx36EYDxbIJlEXrvzQLGmw0gIO+yzi4SmoqZwq3BGYheQyvrCiTmJflkHvNdjziDegQR4y2korrhCeM5j4FTyVfttI+ErVIlf4gsnrbXpq3dNN+kMm00OXrOVd2QeVAW8lPKsABNpGDtxi+x9TzuRoS0LcygWWGZgEnUdqtIQrmKAIiWpwftPcf8KOuDbbf,iv:U15t8mpBR0sgOLVHS5rbd1fqrDPEPNUOYNg6dB5YB+A=,tag:jIWX+U7qddUfPP+G+Gon/w==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYzJrcjlEQWFVWXNVc3Iw
            T1h0VFBBMGJiNGFpV0hLaFMxS2pHMklDUDFJCm02SzhFbTRJVSsxRWhyWng2WC8z
            VnpobUorYStIcWxVSU0vOG5PQ29YM1kKLS0tIE9FVDF3KytjZXpEdTFjTnZVVGRn
            TGQvQlNudElXblkvcVVnYkJNMUZFRU0Keszaw7kPH21emHhwx5FrBZzuU9ZS0q5a
            9i64bS3Vj2iEJ35c+RjgyfDHccpiIkITdvHNL4cOOvcMuEHwRifODA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T03:48:47Z"
    mac: ENC[AES256_GCM,data:+NfWOAS4SiC7ROwQoOV+D8rthZIIf5yRaU3vN6S8XOanTYZpGsh9uGRLWkXl8dMjHl+suq/YK5BqeEyXUrh55Rl9WKtvxY0AL77VX/HYU0PzCUQ5d+9kav5pqXw6N8iivfPxSL4+RpnsLwtKuIiJOQH1Hpm0QGNNKwKGOF/XCoY=,iv:sGIGlSSDO/tLZ4+eualHXhWitHPgV8n9RQ6McmYEApg=,tag:LIJXyCjon0eZd44BUb5x3g==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
