apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:q5P7oQCHCm2b,iv:/snhaakmOivLdkLgvJkn1bv0+bnv1/QtGUqFZvYrmXw=,tag:d+YtmI9ICkh+pxwh/FDtqA==,type:str]
    password: ENC[AES256_GCM,data:UJvLfLsqUMMVLsnKCTPmXFJKY3oNssE6MPvauGKW89k=,iv:I/wvecfb7hUg4PojPdz3rrDriP6/rwrbYsm1tAuHo74=,tag:9mUI8MfnGWozbKxCG0tc2g==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGay84K0Jjekgwcm5NOUtQ
            Yms3REM5UWpvSHJIR2lLeW4xY0ZJVTloVFNjCkZ1cHhtZ2VyeGdNamp4UGZOalJW
            Y08yUXVKR1MwS05sQy9EYkZ3MzdFamMKLS0tIFE0THhoNEQxT3NhT0NmY2liK29O
            aWRrTGlwd21wTEdwRDNGemlwcnRsbzAKAPgByphpIPqIh8DxZTE4ygwHT2CATJpZ
            L2rO8WJnU+dmY31RirHzRJMlQwTO3j3J8Jx08tCp6txL+z91xIhg/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T00:32:40Z"
    mac: ENC[AES256_GCM,data:N+Qd729KfhSRuxBe8kL7VsL74ZFFCpknqaBMaRwjD/GI7k8YNHjR575aQdD4c7UyjmZabwLYjYa/adN1QH77B85ldsji/lmiuQcAWl6l4PdnDGuVjafMm3akc9mFsASmpnQ4eZSRrQJUYB3GO3GaWdlizQWOt/cmfv9OHutXgKQ=,iv:hpyhdrJkKnDjp8aFAQb5l2Bh9DIRR6WlFmdXmZNntA8=,tag:r97TMydLAIjhWygwLsL6SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
