apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xQNsTokxOKx8WJtzHfNy+8zrSGn3gbb8xMcZRhS+wGDwYeLBWPIt3iXlCCI=,iv:fRsgK4Y1Oun5ge1IFAo1UVb1IQqA+KViumIjSAONeuQ=,tag:sfA0/iK7sGaJtnnGAKKrjg==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:kvBfzc+EGu4zZw9/5KFFHRix/R/Jr/dONdkO+y4TTRu6vtCh+5+QmX7sXxvR5F0guww=,iv:/caAqmrAGKEtXKTjZctfd9GlvfIHwR1HQy+3Sr0wp+s=,tag:3TOlPOrQsdBE+VnW5ewGkA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:FxqxSNNVXbrVMWTM8wJI23aZDB+HsuNX,iv:EGdgmXe0F+h2d00J+utu3oawurefmDii/TBPEd7uMYs=,tag:oUCCvGB1W94cSAF8Wf6o/w==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:JEa5mL2QRyFCNjBMqJDN2qifSZFC1tPH,iv:IN+i9n56DnTp7sxOX0RD+bVIqw24AzdExuI4bMNVGn4=,tag:37I3BrljfO5Pj4uk9dgoGw==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:wstn9mIEnN8EMNiZKbU=,iv:9APFPORYxsx4WbXL8Y5SUr00KSBjLO7TzH4aYH9hJwI=,tag:ZZ4sJ9GREPu6+y4CwTqhSg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ePYECy1Cstb54/b26+KJ6+Nz1w==,iv:PugcbqpbJR3Y5FVz4a61VkmZqUHnaUbKwggtwxtvLSU=,tag:XaeEMWSMBwrUMZGn4sG8vw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:v5j8Wvv3mJloHUtEJbA=,iv:+0KCY0p1+P0zW6JMASpRAMA/hVIxITNTdtGADWns0Gs=,tag:JoYggmLKa51tqMlnxrH3AA==,type:str]
    #ENC[AES256_GCM,data:Red4u1xhatpihELcyXxPdjJpqNBCFxxybGebKB4e1pIsofB7M4R+U53Ja0pn1xeYy/IMY6g=,iv:H+/auXTEf/EGLnAWut6FDimieoxdYUPuIhuiP5PZFS4=,tag:qjEnu4Pgh/q66mlo6gkSbg==,type:comment]
    password: ENC[AES256_GCM,data:ffoxH272906dsK0qERZ6vCvPqsHrD6yl,iv:sPstOOfXI/Z+sHOThpVnCcOlyAclDUMCDGub6SpLUtI=,tag:y3LQmn2RiAWbxmEQvP//Kw==,type:str]
    postgres-password: ENC[AES256_GCM,data:AkMIc9hxTThJyzuo/taA4E4fNlgkV78s,iv:IICGJBRFBfVSEfRozvcpjtvlT0fHwOP/K23gJs+tpIk=,tag:XhO/C0Uv7WmipoLx9e1tcg==,type:str]
    #ENC[AES256_GCM,data:Dy+qtaRk2zxe+NuFUEPGTuc12eNBmczvz6LW6iaBqFQ1657foZ/eNc6kHQ==,iv:2nseMiFh6iOdNsHp3Uxs0c3xM9Im9jxcrkdcIak5JSQ=,tag:oHl5o/3OgrRsecSo2A1lNQ==,type:comment]
    redis-password: ENC[AES256_GCM,data:FbjRdK3hXfG3myMAjzEcOp5wHMLWU8tH,iv:jiqKb3nWV3ju+rMq2T9SDTUAGcQw/3IMRlUpic5gmPw=,tag:W+/mLEZ4rtOVQU13895VfA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVkFhaTJwU2xUejdTVFZJ
            ZW1qSGh3OVVjcUZEWkg4TEh1dFlxMEZkcEgwCkVLM1R5Qk5NT3laUkJWb20rUEIw
            eWxFWVd3Tmk1S2lScXBLK3VjcFcyVEEKLS0tIDRkOGc5YlBBZnppU0Z1emhDKy85
            L3ZkVWkrZDFLQmVzRlRqK3BuSVJoQU0Kie1CR1UrHb8xUNm56RRa9L3H2yij5VSf
            EzcQrzpmD3v6RjeIs/yKOQ28Etyi17dT4QZxDp4Xl3J81GskSufxbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T07:50:11Z"
    mac: ENC[AES256_GCM,data:kTEXU4szt8Foi6Qqa8YpRUW4T83qv31pxOF9rs+Mm+mq7lRZdVM1IAkCgC4ptkStv7HIZ8gOWsL1FcRTpTkrfQ7GOEgnJlzARpzcx4IUBBpDz52t+Bp1plFT4pHWf81NvvDTmeu270GjkNPPk/W9DzQsLDcAX8W3oVwk2x8/IOI=,iv:ng6VVedc6HRkxB6Qjgq8ywMSCK+zJ+2RRAGMbmN3KnM=,tag:md8bJOJDEJN4pR2wiHUv5Q==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
