apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:r5KiTtMceSz1uXOEqebxHFGlgoJ3Nu7dtpnxkBNg8tKy8uKmUP0VKVznsXxu/1FJ2kcS9ftySEDuEqeXPQ==,iv:/Lg1rlpKK8BIbJVxfZxZqi90YOWXIdl30oEYz2vUOkA=,tag:0znRA7M7hlh6OzVbZYfR1g==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:y7Ypu/C99BnT5cJRah7JRF1FbnJQQ6SQs+0UpAzMiUIalZRGiEbAUZ7A0JJflsoJLEg=,iv:A8NEwJXmC6ltbYFQ1LOS9Sxm3hZastlgcppLD/E1cs8=,tag:8fb06hCkOBKY0QQ44h4KAQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:fRXnQMNgP1jZasOSXeHzqmT8u6B43n4n,iv:uAjmy0AQPhZzYJkokKdCJH0ALxuuWIoMPWFhlH76E2I=,tag:lRiYt/8driPbD13d4tPPng==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:hi9L8CXeLRiHf4FOyW8=,iv:ykz3BLKhfFwJszu2p79BvAs6pscRNdzjiWHoMZXYYvY=,tag:0pqQcjQ9x8Z37QYUBb8uyA==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:a9fgc8FrJLscYWwW6NBr/qh6eQ==,iv:L5mfgyieVuDMa1oR4GD3hZ7ltLzkbyNPDm+8ttNu6no=,tag:KxqfHhTG/oF1KpFWcd0fVQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:ffvCmjsyHdWmt9qkr2M=,iv:OoDcwGuoYcdb3bfGbG153zjsa7w+zYmnc0PPkeas3k8=,tag:1QLuOYq/IikJlINvPwvuQA==,type:str]
    #ENC[AES256_GCM,data:KqDvRJIMD9FqCjRCeEDMjOB8GZDWHCtX9tbvi65wfvYKpO1T12o/RQnSueU0lraVXhT343I=,iv:5zG6iwRtvcZ9/XUTo0qpNx9uXqOv5sR3t0WeGOkK/qs=,tag:XSi5eOv9c0hztHEf5qUA9A==,type:comment]
    password: ENC[AES256_GCM,data:1XxcBfjcJXuzwbxxM3lYfOu9HuDhb3Ef,iv:Tz2GlDckfvapGo6ASd/Eurq9vKZPqLxQClCTQXjY/RI=,tag:j1uhsQqBUcDXgJKE0s6Rig==,type:str]
    postgres-password: ENC[AES256_GCM,data:ExDRFok0paqLjR7TrjNcZk92MF8yKYZI,iv:IlwlZzwE5Fp03bQn3f4nBQBVx4+0XVmooDtti1t+hwg=,tag:8qZ1fhszIGmfJ6pRUXGZqg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUnpLdi9tcjY3V1QzdjF2
            cHVGclJJcFVCWTYrVmtnaWpHeS9yd0NZL1JZCm01WTVuTXFEUFRkUEZSUHFtL3VE
            SUZxcG82MUQ4TGRKdXorOTlCOCtxOEUKLS0tIDVPOFhtMzJHMXNGdVJseXk5aG1y
            RW1KdEdwUXI1UksxREJPNjVEWkd3MEUKb5VirVH6DcAwhxO6+jICGFKGblxq27o9
            7wFlphgOq5WBAMtBkx6OZp/Jwou7TV+fTi1NNKnDvVRhdo76FqfaQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T07:11:37Z"
    mac: ENC[AES256_GCM,data:8F6G8BRPsUcLQ5CYc2YXGO21VAJt0x8hrTU/dVsy8r11K6DmIFIdq+UCDTPTBlRmHwdTDjyP2ryElBh1Kx6omgUGPZ3r+HnDp8LRIJxf7/NfniuzhH2A8FvMzPPmpsVIh+RJTTIcHovZztYh1tz81u0CVy2hslZo8u71bJa+Fss=,iv:hZ8LjcP9AaD3W9xNS5jlLs0kSTK5k2NE6N6dg+CYBJ8=,tag:84q643D6rhnlkeQgPHyrWQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
