apiVersion: ENC[AES256_GCM,data:tDY=,iv:GWuBtpw9nVs6IVBA2IP7Vq/xaZKyOaYYQZWhFIdW5SI=,tag:6pCYrdT4DWieFAb1wbwkFg==,type:str]
kind: ENC[AES256_GCM,data:o7FtdVd7,iv:Oq6OQpDrrVe1cqMFsCuuH49KsqGzJLIiNOstNXrlLLY=,tag:v9M908aqs8gkGK6jBjmqqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NHaSSul+cAVe0d8PPY8nk1BorvsB0A==,iv:SR8PWzLYwCjNCRShviuP9mWC8Qdk2zFdGGtZ9YJEg54=,tag:rD4pQcsUofIObzB2pvBFjA==,type:str]
type: ENC[AES256_GCM,data:/MmXRxs6,iv:Si2oLzFKtY57cZss4r/GSeyCLwzmOsGU8NLfqALPPlc=,tag:q+9Na0mpUAz+30sAU4G6Zw==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3l2Tlt8tacYJiu8=,iv:X/tb3uM4KM4VnC9cvau5s6AKwJIaAGwRXc4FZUg6kqc=,tag:HhpYxr26nrP6nX7FCICJKg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9GSIxYNlr854gIj8EaExO7iBHUjAPZcdmc7jKdelwFA=,iv:r+/ChInoqyDxWE3knBFQrasqUQHmT40rZ5ObD+bq4jQ=,tag:Lf3ZMfUSrQqCc6X+P/kmYg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBV2llVmRaM09OU1RJZFB4
            MEgrQ3E1eHhMN0h2L2t1V1paQXRNYldOOTJzCklxZnV0SFJZMUlrVlVFd29ZRGFm
            dWlWQUhJOEJjaGhPZGxoNTFSV01uK0EKLS0tIFAxZjNwcUl3em1QN2dNdHVmdlh1
            NU45dzdrVDZpZDNESldIMlJ1OTZCU1kK9Z9P1j9bMMrsS49YI8jVBRL45IBLUoee
            2c6ItMtufMT/7sPiJh938fTRid6BXJTBRr/QOZuqwi2yEowxztJHEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T07:47:21Z"
    mac: ENC[AES256_GCM,data:OaGynsB/BNmEUodw2IuaCh8+/oYIiikUYxPGydNEkP92/pVI5Zt2RGJkz2ZBFyCI3GCphuFbNWo07wiGaBnUo/aIXJqVxJvtg2l8W4hmVVCo1ONZnmKiNErNFdzr5jV1yQfI2LVJ/D4ChrtMSQmfqFmfcI529q6tABb0GcBNR5k=,iv:AMm7j/rwjiGe0JxXFS1S8u71wlvrUlyvCFcXAQaPdDA=,tag:TEL9Bw6dZeW4+uN0eW9Zew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
