apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-exporter-token
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:cCP3V79IfT2uUON2FtDAqP8K272/4+KXRHNih+AzChF1uwP42fFwdEVRV5VIBZN6yQxhMhw=,iv:5V5rK5SfTXZaQk6L0eZSkd/ysLGL81iRzzzmnHUCJV4=,tag:ge1StHtdolZK42N7SsFkhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa3AwbS9tUHhxWWM1VXd2
            SS9lbHdIbUJDcXVPbzFrU25iUVdRRWxGZDBZCkJvalRLdEpvMGIrU1NpaUEvTSt0
            QjdoNytmSCttNzBlRmt1NHIwT1AxUWsKLS0tIElWOW5RZ0JxeUhqVjhJcHArU0hn
            RjhIMWlTMFM4U1JQcHVjUFpTZ2JGVWMK7VK28TavFgInH+5EtrV2uZlh6MBoVX4/
            McYgChLjxjQawHvz4ohu95Z0CIQV9wr05xrCGeAttrcx4EuREznLZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-27T07:21:21Z"
    mac: ENC[AES256_GCM,data:HzyZb4/mECqYCityEuFXQdNSNQkoS5KIJL0jN1GLJcw9Sl6E35MXJjeNksZhIKCMN6xZt27g16L/wsPC/02E1KsgLrEOrmjb/WhicwUgvoSGgNDnYSqmtemfAAA+bIKVd6qEtme7mezgPX3NJyUW1QHkvejO/ES7hevPBYaVKCk=,iv:iv9dGmFwGRAksHlbMqDsBzKta7bbc533KnobdogOUnk=,tag:N18bk8xxTxPOazxN+YwEfQ==,type:str]
    version: 3.13.1
