apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/authentik-secret.enc.yaml
  - secrets/authentik-db-app.enc.yaml
  - secrets/cnpg-minio-credentials.enc.yaml
