apiVersion: v1
kind: Secret
metadata:
    name: mcp-tools-secrets
type: Opaque
stringData:
    GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:NQoAX3iZRiBxgmWcL4+i/1tnSjfif/17QoQyJeIFDrzewi/vWib2JRxab2MuFw==,iv:t9QPznV9ww5S3+yS7+i7m77VWAHweDu3+ayktq6vrKA=,tag:tBvO5ZL5sK4XH3F5R4WrjA==,type:str]
    MCPO_API_KEY: ENC[AES256_GCM,data:vaPWfC6c4yaMFfZrAZAkvUTcFm3Q30mbkVIj1D2VkA9bLYs/5vKRGTpZ8Ojx6iI8ZeRp4w/DT29buiSJyASFXw==,iv:VRqGnP/HCrHizxDnuM5tlP+0M7Xm0teFuxahuZzFNK4=,tag:iOZEZrSzw588z2ed2Mqhbg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnYyVXUySEkyTGcreVRN
            WExNZlVSd0EzK2luVGFvekxUbVZjN3pUNm5zCis5T0IxcnFxUVFzS1d3clpCK3N2
            Q0RtK2UxZjlYOGVtbCtwTDhEU29iR1kKLS0tIEo2L1UvV1NzSEdCdDN5c3A2MkF5
            dW1pY0ZBKytBcjhHdXJMcUNpZ0pDT0UKmM+Xs8orjIze9jjTclAhCeHFSF6p1ZFF
            4KP9sV9oTJshvG623kfg1cjjcGO0byg61Ptp0WdbSr3JLm9KBJAsEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T03:02:29Z"
    mac: ENC[AES256_GCM,data:xK+ycFLiBZYlgl81er0E2rnfa8Dk//+4Y5wxEzP5fDBQMM2JqdSteH9ZO3AY2sD9xmTuYicGPVU9ieztq0nysn6eHMK9Gm0kCw8YhE+jwAyWN2CfLD4u+D3v2X0cs1MD2/NjH02Hy1JJqo2ojTSIaK9KZybXKZO+RXnWWqvrThk=,iv:f4lqCIVkMkgZFA5kjvI2m1fgk9C1cXAH4czrhi6+0V4=,tag:QHDp5ReR0xqfS5xrQIGIhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
