apiVersion: v1
kind: Secret
metadata:
    name: librechat-credentials-env
type: Opaque
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:42AGkgwlaz+JagSEQ7SUUNAB8PYoU6riMPdpR2MOAYDtL58buYslEOTt3DpMFxHySbFIMaKmt/840GbzRKe6pA==,iv:t1AhjmxjjGUzNHnu/IdfuPgcBtiTwSkU/1I1QbbmHRo=,tag:eyvfwWbJrp9FEMKEmGsNxg==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:k1pZiROZ2W+hd6aQEyrqDRqWU9N4XBM3QWW1IXA7Lxw=,iv:746OlajbQ2pTXA0mX+p3D3OGVrcUG40p2POBZfqi52w=,tag:ZTl8Fey4S1uHwwkI+asUMQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:65EH4SFRR/hTtpgLS2AyD+uAVxQ+xGJqhRJ5y87SBPsV8X26kOr/yL4zs7Pq+Lkv28TGP2R8gNIoD+rERrQAwQ==,iv:El9QaeKcxn8OuxQYQxFZlXJvv30wfKChc3goLpIamd8=,tag:JO19zjaBRg04ttvON7edYA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:IJPrad5MgKIByrsKhfmMBtqUH2wzZhALl8AvH06B6Q3mcLPhX9wVfybFV/NVoJ5vmqoHUbB2cMvuA4TFVa4WFA==,iv:UkyOhtfKFMjlAoVyh2kppHUDpBKVtzV5rU3YzB9tUWg=,tag:3nDoQ8fDQwSxvPwijx4Xbg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:JhGEXKIvnT51EoquIZn0c60hwDlL6P4y1REOnfcqXTdxq2F1gXKVQn42AOc=,iv:nBisVE0gbkk3pEcwBTSbnwhb1YrCBdcNBE4QEOB76ls=,tag:Fu1uKrO/mIkuhTR0NQMtpw==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:siuY4j9VyCifBqpqDC04oFaV6h5qMSttp0+6X6hb8MiAfJ8esbPoT8PhSnIs3vUzcqEEjJ9CAXiE1VmUEZdxEJuNFywcqoSYZPUfKvdpp56fwU89PRpAG5nYNr5Z1w9V3A3TEvXr/8cDE9w5n7mI1LXtKBO+gsDhj0E=,iv:7O5yMv70JlDIVTozClXJAiaC4AwhfTRRwq8WlMnnmfw=,tag:/bdip8Yv+XDlpP3f0vIokQ==,type:str]
    OPENID_CLIENT_ID: ENC[AES256_GCM,data:zMUiEqfMhdxyF10wPz9P9TNJT9rP35sRXtHMayLMcfs=,iv:YjfjLweqGX6T4tMj98G4QGTOtsbo3Ps04HQ8tqB6z+I=,tag:i1/SFGiOXUnRaHvp7eHljg==,type:str]
    OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:w7c/RsZBBEDZSWMhb9HFt8JQ9RQT090GUDNaKiq1dWJKeV85chixEVsSsDBVvr93Mor2fEp88SsoIZ/GN+Qyow==,iv:TNV6dNfq5t7a3oaKbkwfUa344mtsDgJD8T4QzzeDey0=,tag:H8Ze39GYDPFsF2bK1zcBNw==,type:str]
    OPENID_SESSION_SECRET: ENC[AES256_GCM,data:UblWtjxWfvo4bV54tTZjsPvnHJ0XV9vXua1TcQFmXDzmY4Dw8yr5UiJc0t5PpZYxhmIvPtxwlxf03blT4Ej+RQ==,iv:c+7Ckmhhpcbr/7GCufcKXxIPwqTb+CHPbo7DhBs4IJI=,tag:1QdabXM9oRj2/sG0lSL0Cw==,type:str]
    OPENID_ISSUER: ENC[AES256_GCM,data:Jr3Tzr6rCqRSDSC7wy5xo0tDYug/BY1R/P5y/5WJBCG1640OOkrDRXY+Gw99fTS+FNdp7Q==,iv:LAXG6RXUfvSHT4ctsAE0rKdwDyg9OnGZ5inohkXNe1w=,tag:er52nlfGdeXwJiqUUvED9Q==,type:str]
    OPENID_CALLBACK_URL: ENC[AES256_GCM,data:TOu9rOBS402oUzE2aWo5EZ9uQQqZ4A==,iv:H8GaOWXW5nm2aw/Bnx1iylsDx1BL5o2a6R9hCxy4MMY=,tag:vxjX8ch3l/ltjUYjgbQquw==,type:str]
    OPENID_SCOPE: ENC[AES256_GCM,data:v9nZ5ArW1Vh167SX9Y1GwkNjuj0=,iv:weGkCCgGuYmXBT/hrmkVC04SLApBXSf0rkPq9O0Jqy0=,tag:tGQrBidJwUVRHMsu1wLdOw==,type:str]
    DOMAIN_CLIENT: ENC[AES256_GCM,data:d+1ydwfdT4dWDsefOiYIkQsI+K5X9TK+JUsJ,iv:arJnEp67cS2pRoLA59OgYngdd+fE1JZil8dXDUPDSm4=,tag:kqwWWKPWsXRMJn2vuuOc8Q==,type:str]
    DOMAIN_SERVER: ENC[AES256_GCM,data:KHtmIa2868+Br9+qLVahhjbPx9NRksO49uNv,iv:PqXwLiBeEQviY/HdO79sSB7snZWzV0zWFgqs1qSjjz4=,tag:JC7BjcdxT3VLNZb7R0hDQg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV2dUVS84VDVNdFBUSTFs
            TGg3KzdZMktNM1dBNmZWMTRaZUdENit2UGlnCnBwWTFnTEpiYUtBampwdjhmdm1i
            UklKckxFZm51Z0x3c0ZDY3ZsMm1DaUkKLS0tIFpEWEs2UEFlWGY0V3FCRUtLQ2M2
            bjdiVEk1NHBDTnE1L2JQdFZSYW8rV0kKHucOLYK6Sz5ZfIKqY5hb761tT+mDl+64
            DDY65g+gr1hjrJibo/ez7X4CDARJFDTflF204PdqIjmaoYE/Y9VAww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T09:23:26Z"
    mac: ENC[AES256_GCM,data:s3cbmzmO/BEsOE3lHmsb/SJCSUUx+JryzeNzJiTXwqexwtkSuY93eVQpjIXZJuEdcZ8ZFj9wgJi6aQenq7OvTvbGuK7rnAAkxLZ65wy6XkZoUdIAvvA6mRg+GpmzyOQ9INWsXsdiDycHpD3704sIGvdIj3Z0fnMWNOma5lRgzxU=,iv:h9NT6gBUES83JMmyuao16CrHbRAL/XdQdwAQ/1BjltY=,tag:yozJW/fXbdOK4o1uog/AFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
