apiVersion: v1
kind: Secret
metadata:
    name: myduck-superuser
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:XyJ5BqKpJIpwvKAQwx5o7V+bdOabYQrletRXmIHNNcw=,iv:E5SniQqqSVcdOlXwVgXsIH2X3nFiPA/aTrgClnZWW8o=,tag:40UVA3yq21n3Uy02Fr2sIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YUJBS2VwMjZ5MFZnS3ZE
            TGVXMjFPY3FUb3dJbldXclU5SWpycFdTeUY0CmNTcVYrZm9QM2t2bVhPemN0MXVi
            bzNHY0R4ZkpiV21PTmNLUWdVbGZRbTQKLS0tIDQvblRQWUlQWkhmUVFCQzdCWDVl
            QlorVThPcmoxUU1WRHQ2V2xGTkx0UkEK3vYrQs1XW4c+hyUBbXBhoyxe8LMsYFDi
            76tSuswazdiuU9Uy82f4ITSLoYwv4lcqjI5rHVDSkz0Agiyk8ZkEDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-05-27T03:41:31Z"
    mac: ENC[AES256_GCM,data:8AX4DJvMwt5jl2Oy8R0QzQ1vnSsEJyXBebGNT5AIL9YicsEnO5W5MVznuhtlMkweuzKsN6DrV58d9ibYJ17f5cVAXuQSjhnWncj+SdfN7/E3tIodamPjF0qbNUiIM0yNDBZB+izzpNN7CpMwNArsVpAsYKydXBzcr+CIFp1TdoM=,iv:KKgq4WAqQvMUFgzbSF7qyQCvbArCquzrRDHGQ24l0Eg=,tag:OUIDmXFkcRe3p4z8DfSDLA==,type:str]
    version: 3.13.0
