apiVersion: v1
kind: Secret
metadata:
    name: vector-minio-credentials
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1+y6DU81CmIERbw=,iv:UpdWOlat+NRotMj7uXwtj8vT6pef1sp3fmRihT6rkaI=,tag:N/vvbuG6QG4aONO929iiRw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UXVjFp0bnO9xssK+B0dO+L1p1s0NUmTCfBEogjDe3v0=,iv:YnIzcMSusB+h0JAuSk70l26kjOYgE+JBqO/VAnP9sfg=,tag:TZonASqRiWbZgZxKG54v7Q==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UzdoOFJRYXRJZWFoSTk0
            UDVjSzZzTmZLYnZIN0FHaHE3SlJtSHFEMUZVClU4NjNod0F0bERBYUQ4MGJKWDk0
            TU9paC90bDlIc1dqdHhjMTlFTVcyM2sKLS0tIFZMRW1SYWdHb01kVXQ1ZE9VdDdl
            Y1FNbVUzcHRPaUtlWlM1ZlpkTFN6ejAKFkQsRZtDpN1iHfyeSTGmg9/g4lNpYAmL
            MyrdUugZVxHBhDtZ+6G5ZEu12LHljukzYLUVdA4TQCG4OIODY+3O5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T13:36:13Z"
    mac: ENC[AES256_GCM,data:hpTzDxivWNrlZqgAM2naiUmJQVDrBQMpvPCUlmjbzHGSOwTWqZJivVS1oQqF1hXz8HqKoOtMiHiArkMqjGoGKSBW67JX3DgyzMWxK9gF02j50ec/2bMzulLvG1QzHmOokzeG3mUflnoImusNX6Kcl9i143SwW8L5xHxrBeRe32k=,iv:LAO1ixEb1Pr1EoFwmYAiifEQd/HynMsirMD7uD1TgJU=,tag:hTiwvLH4elSRv9I/6WoB/A==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
