apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:weGplseOmA1nJNsTcMEXrmai/GXW0ipmPJL6/d8Rxbxg74jnnh6V8aKNMC0=,iv:YA7pZh4T3mKIBVZnPR/uu8+s1VLf6vT17ALjCdt1qiI=,tag:cVOrPzQeDnpbgimrQxBOmA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ao9cBfh/id26mPCNrMykogpPoBotp9KKC37enqMuXTU7qi2C/c/vUjQsTqCid7C+n+M=,iv:0hJeImAJfwtCEppir3GUBMc9ONiOkZ+3q/lqfS1raKc=,tag:sC7dQyX00g5x7XFWi/0b7g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:SjNyMe/Q9lWSvRSzmDTxZswY4eAitJlD,iv:iEpu1SzB2pkG4xUk2bVSKpxQbO4m6hxqHvXiRY7S5dU=,tag:HIBL/3/gPwYPZRnu/knXqg==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:u+mVSj5RIzfigNmKYAHzQCWjXkcLrnpM,iv:MiHu7/+zQACcmeW9O/mZyXfVq76yeM4569iOgYi9tAI=,tag:i0gWDAqRdANpT6peejzjTQ==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:P76uq3ZIvjHzR06LEBM=,iv:Vak/lpkDs23B5Ve7QuwlDtzLcjlXJ5PdR4R9t46pIG4=,tag:+1Mz7ObMcdKhzUZjoo9E4A==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:Uw62OeXKq8yM4uDcpCBPiQUmIA==,iv:MBNKc/VlvYTnccB9pM2pXY1zQxnXn9tVPydyRa0queg=,tag:v4744IKjIj4pcP7EZScuOA==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:UoHxlw1n8E8oVg/GyAQ=,iv:m8ljNsMasCgtokqjipYLxpYd2oHavb37L6vSL13I7zk=,tag:zrhXZob/dvB/FMcgqppEVw==,type:str]
    #ENC[AES256_GCM,data:c29LL0kytZxDlQRbS6q9NlEJnUBl1pNZt4PrT9m2zKa1VW8c2BtQIu0x/FucFv08KZrgIks=,iv:dfdVVSFoYw8yC7PMYX2NF/iMzBT6Jlay4t87jzQOzE8=,tag:6Sd5tLLdHVaBF7M4iWzQ1g==,type:comment]
    password: ENC[AES256_GCM,data:IwlmWBa2K3ZwbGgFUrQWw/X+CiJKmVal,iv:OZqOJf2pzlufnHhjI8M649QmGW0DaG9dC7qdvgy+q/w=,tag:QNYzeJkM3MAePFGl1yFyfQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:YB0ZiQxJWQIxvVGnsTDxDMehnnLmsjkD,iv:VRrrkLHW9tqMHAx/SMFEm32YVkWhakndYXLHkQzXPHs=,tag:7gv5qAG+tbE/rXcBefUZyQ==,type:str]
    #ENC[AES256_GCM,data:mlwNYPXtKFS+QQS/iWuWfxeI7fGgRL54p/aHmiE7M/jnDO4sTnu3U9LPyw==,iv:zv9wL+uTlsLgnPCh6zJSacn9g93/4pf0XJP6uV/ltQM=,tag:rsiVKBg0K0ZmyJM7TbDYqg==,type:comment]
    redis-password: ENC[AES256_GCM,data:3M8RUwvASQrUHkYF05MsNHiRUdgS4b97,iv:WsKmWbtiQ3ZIOUc+smfIaVedUHk9IJY0WqcYG5K2/yY=,tag:f7kPI1d/P8GAnQIDYPDh4w==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UEZDVVppaHZNMkhxL1JM
            cVRhWXBzcld1Y1hhc1E3eHk0TFhhbGFBaEUwCkhEVDBWbm1KZ3krekJLZlBxQko3
            T2Z2bmQ2c2xjQW9iNU8zMDlXV0NLMW8KLS0tIFNnS0E1dHJoTXQ0TllxTXJNcW84
            ZEx3MG9paDZMTkZrRytMUDkxelVQQzgK8MCXoKdhoUC4Bt00hLrUzQjz1l9wwN9c
            jo2nmWIydvat/P72G9MiCmAFkV8akFOX0aLjEONmNvMdeAB7ZefVYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T04:45:41Z"
    mac: ENC[AES256_GCM,data:nwhip8Dwc20EsaxrlOc+EqUQdR6AUQ7lkCLlo+PZxr6HuaXVDeL3D4cPKOzbUqto6elfYwTv5j6zeBV0LVyyNujAZPzRe0ghlbyECceqwuEf8vhttWvbU8Ea0D/QF0xm0r9BE55tpHrEm/GkbLv8d2BwxuRetEQEWm9BZ9AkEmk=,iv:LNhR5gmlbLzAJk8VGiInH+/XtNnU2ExXGW1WtUV/Pf4=,tag:6vXzNJKgwpugXTUrJFLv+g==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.2
