apiVersion: v1
kind: Secret
metadata:
    name: scanopy-db-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:EHpr6eg53w==,iv:wtukkGRqieqaNWX6e3lsIvMjr3t0C69SYDFSf0WJ1Vw=,tag:9OqZbBAWozukcMhZ3O3C2w==,type:str]
    password: ENC[AES256_GCM,data:xGL9inFNaBANVeCHt7kohzKBJGzMjbR/w6usnx8W9w==,iv:3HjONw1/Cov2RadZnYGIJh8JboJoNg9HH/HMNLzBugg=,tag:A9eVno0Sm1+eIjgjTMYR1g==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcFJxOE80MEwvei9WenNu
            Z3ozYmlYNE1uUmZDRE9zOUh5cm9aVkI4b3hBCjBLZjZBZmtOdzlhU25WUUk0ZUN6
            ZXdWVENrNDhaelIvcWE4Qkw0OS9ucmsKLS0tIG1XRzVIcHEzazZhUGI5aEQ5TjE1
            Vkt0OFREUGY0a2JFSk5WakI0VjBjUzgKcK2rHwJVIEc7Uu5hjVsr8daA7J75wJ/i
            jZj/QTVnYo8kpm1oQkex122ebkt5uq3wAeIfg9GLwJ9/RU945TjKYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:18:42Z"
    mac: ENC[AES256_GCM,data:i40Jen4MfyORXT+uxmOA6gLiIlPNxji/KTl0urvpckOsGsULufZDeVGydr5k4LsdO3JmpiaH7U+4kw6iMaAONODX2Zv9WBzYsiHKuoLZX2MyeY4NLIDbo1zlOGOJ8vkKRNthJ8dNbdK7vve6bvvvlhk5/6YG5S96ur71Cfm8rCI=,iv:yCbNbJHlk3CRZOreVjdrTI0aP/YOw0EUFGbOljOICww=,tag:zMm2aHdXRMB4wbgyp4MD2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
