apiVersion: v1
kind: Secret
metadata:
    name: scanopy-postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:urScWQ6Flw==,iv:gpYhFcgcbI+gx0Pz9rRoe0Yj/WNJxRoItpCTa9Dwrq8=,tag:dWyCWSt1wNPsS0v3moLqsg==,type:str]
    password: ENC[AES256_GCM,data:y8FO0qvy+fX01B1UP8O/UzLH5oXcjqWGVJfkEHE=,iv:5N0U5Nce9WnDO29ZScLPmKxPAxvmn8LGKATa2HPuMbs=,tag:QOLWH/SQ9M+zATOXoGpyuw==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2c25senZTQTRzdmFuOHd5
            dHRWNXVMbmp1TGZURzZ4SkQrdkwwdlVjUFUwCmZZZGxRalFINnJiUmFDdzFrT0NO
            cTdVejJ2UU9vVjQyNFlTL2lTZlErc1UKLS0tIG5EeGsvc1lwdVFtL2dlT0x1M2NH
            djZLNUlqZ3RZKzNKbE1lRXhVWGN2eUkKsEd0phGS7Q22s9HsAE7tVJVhLcKThw3X
            TljTW18Z6SqoUjSZfQkjVmb/z7oQiKnUOfOIUKZ2NQ0qji0BC3rRRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:33:40Z"
    mac: ENC[AES256_GCM,data:s8SKsmYVE584odCwujegIXAXRnRvtunlclLoz7OLMN93XaV64d8MxFuuEQoRDW4vd/iaOnGKC1YymPilGwfT886rEyub/Wi+Sdo9IjGVkBHclQENPqzMEhXBxUJlVfea06PcmEjU4qo0Ev+FsSshrguVqDW2RmNGCgTLE4GJj54=,iv:EDdzGVZU9xwSA8x76A45rbTOqYEFNqbpN1qN6gU+TLs=,tag:z0VCNwagSLRh8zKtHR6yfQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
