apiVersion: v1
kind: Secret
metadata:
    name: scanopy-secrets
type: Opaque
stringData:
    daemon-api-key: ENC[AES256_GCM,data:0WwlUzUU29miPH7eaEaNF09NbNP2vp+J9emorTtzsooC9+ZAKLY5RAcJ7cUXMF8gMeFVA2uRfr7d+tWwcy8sRA==,iv:f+mlML4QGHBxhVqN8l5J7ZU9ZwmCCqnRh3IVdUxYHeI=,tag:zEJZ6vuzYRGyKROw4K0dFA==,type:str]
    oauth-client-id: ENC[AES256_GCM,data:Vy/IVesOKw==,iv:L2PJu4fao1WDVJfuqMZ84RAtcvkmEkZRxIegs/N5W3Q=,tag:F231hpX2TjdXYoORKgDd9w==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:VimsnX9E0AHJj5EigywrjlHiR1KMji9pAg907ExlSeADpgATw+0L5O7PkLcrOstgO5EhFAC73sUyhUbm,iv:km5102JJWxMUUaTu4VgfAjuQeBDojKt0tVVHsDfeB1k=,tag:Y33/w9eNQuABnt04q63ciQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOE1wQ0tZM2kyUDZyaFVu
            UHR5cVl6aERidmp2NzJkbWtpSFJWR1p3Q2djClF1WVE4eGRkaThOOTRWdnpPbTVQ
            WEpxSHdidmtKVU5sTEVPd3BiVDJzZGsKLS0tIDcxQ2tub0l0WWdOY1VWR2ZaVDJ0
            emxQcFhvKzQ5SXFCaTg5VUJwRnhkVUEKBRCEGdw99NQqECxp6OS95pObU3LcqcG9
            OtwwOS+xm+UeLElQOK4bXO3LO0d9u0QXvKQancSDO++DHlhTrzzDqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:53:50Z"
    mac: ENC[AES256_GCM,data:rL9GZnmHq7/p4jn5q/rEqwLxGN6ufoaGYwTr1HNoY4Aaaj/TSv4W8mTcNr4nfHEv4QImfmkpXcPnyL5ZTS31uFVJuK6BYqrMQ/JWPSHhuw4g0OX5n90m7saxfpy6I/CNgsxIoYhTckfF7GesRhs5U63HMPTK9nL8Ev0TJGW6w9Y=,iv:LutPVQjMM1VNqyMGrza7C/uZcTh7sP1E0/5lPI+DNoI=,tag:5uYZxChhR77njrV7dVGTTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
