apiVersion: v1
kind: Secret
metadata:
    name: scanopy-secrets
type: Opaque
stringData:
    daemon-api-key: ENC[AES256_GCM,data:EMZ9KRKULA11PNqCVaDSqgOgjW1CqLLK9mIhDYIrjidL0flKKAxPXFPMVNZ7F0ZnhC1eSO9IivpxdGiV3vTayA==,iv:5SJ6g638DJF91EAgqN3u0A/hDXcBBVyKN4VuoB/Q4zU=,tag:tkI90fnyhJ+Uy1F0MbwMrQ==,type:str]
    oauth-client-id: ENC[AES256_GCM,data:Ly2dlMYnTw==,iv:D5Fm+lrxCxJZjJND0opWynDEWNpKkYgOTCz0ZXdkjJM=,tag:jh1cg+UDCOMhiXSZVDoZrg==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:D4wLp6z6yMXxkIpoRuPR1p4hb5Q91HvyGlPzTS7y5nIci64CNqdnACC+Aozwv4LXiy6iXHDD1ZFkSRtT4+O2nA==,iv:GOUeqoJ1ypP5O2dQJ3gIltkeCjcxVvA7JSm7kdr734g=,tag:o5nFivomiyTi2O4LjGnB5g==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZFc3YUpKc2c4MDUyNmY0
            cFNueXIyeHlJU3RBZXhkVEtHc0tlbHk1T1hNCk0xU090em1QdDRtUy9La1gwQ0lx
            Ym1pTkpLRHJxWXBOdlNHVGRxZGlBU0UKLS0tIFhHZndicGRlVDdhTStYTGRGOW01
            WVhsNGNva2tQbmVpRnh1SGZrQVBPUlkKf5W6DdyWX3i1J6nh8nauOSU8E/52eCz9
            OUB5p+KzsFBqXmizazgW2vkkWYWAylEr1c9ZaMgRUa8rn+UIYFvZUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:26:30Z"
    mac: ENC[AES256_GCM,data:wouX+e1Qpe+L5tBlTTd3O6yzP01XkoXIEhkcWKRtEvA67nRze2wgTH1AhzGESIpUXwg4zd08b0pqBGAvBbJMMTKmgNNqoB5uEpjDI3eAoxygizVIwKZfKJakL12t0QN8Iz164bU10VYEvM2bpPXE84C8iXibBUcUCX9VZ51Uf3Q=,iv:Ep7Gz7+75UsR/Stiyz4VJBciwghsY3O2rMz4pZOCGHE=,tag:rrWCJgmhHxzbwoOkdAvCUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
