apiVersion: v1
kind: Secret
metadata:
    name: scanopy-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mi94q9/WdVVX7Ib5+W/AAM3vIGo+Gi0/TqZO2pgEWcb4TnMOkaJ+W+SGVrjIhxggF478V1xgoXsfLWOPdb+OeEIorgOT2pMN1JgQxuYNwd2Ya10Otg==,iv:UFAL7FcKRBzgvMFMZzRtfiQ028wNflhaDJq/aTUL0GI=,tag:uDtGQAizMFahd5EXjS4L6A==,type:comment]
    #ENC[AES256_GCM,data:jpx0qA2kPktSjpmEKQa7OF++3ugjWvVp1isWw4KKaVzYdAb3vCBUVfkPd2BBTMsLR5KHLlLil7tOZEKV/kvBlk+G95iCwo5ducrHvKusDY7eLnCeK15ZoFAHAgpCyFJfdU5u,iv:2TPe3//RR8094AM9SAxkxUNA0K4kosReHVhSgDOvlIk=,tag:lia3EGHCnSt7SKoOhIkOdA==,type:comment]
    #ENC[AES256_GCM,data:TDC6HAtusKFMXL4j2r5vEbZXR0o4KHLbLqZMoY/mFPjXCGFMlG8lKegOmBBJDvmjw0aJnu/oCewfflWYWLBqKSXDYamxRXQ8+e5xYdi9X491o34SFxCnwRwM0ZpYCWClUjnlzh7oHA==,iv:t7V+emQekZiiHLOB0Rci/WnkiUYezhq6fsM65qajLaU=,tag:dWJ8NwNHIVbfiOk0CRX6sQ==,type:comment]
    daemon-api-key: ENC[AES256_GCM,data:Y6lS9VZGX2K/VXmPzjXSsNyuYuQI9336g7uJUA==,iv:+pHX1NuUxmPhJGopol24DklMwOhMk2Xvu+eQgU0rNk0=,tag:X3Ji5rjVUikM/Coq8oYaUQ==,type:str]
    #ENC[AES256_GCM,data:+/WwCTQ+ZoMtmbDZRTp7ELl+4zM2JvErsEaxO7sDiaY0wKmE9oHj/bQUneJ6kJ9Qcj6XBCdPYClEr5nLeNS1T4BTEId1SOkLlbfkXEGtmDsJ+iQ=,iv:MaZ3o3GTid0AZf3WEGlPRn7rN6/2+Z7DYDeESGYzkMI=,tag:Ido6mwmRhTRUKC4iVu4JEw==,type:comment]
    #ENC[AES256_GCM,data:KqqLBvZ10pmI+rechElkIJ8Nzg9p0WZ7VyjpHn2naXinYlPKJ+sTFM75yZJS4CXewGhzj/V0Q+pM58NC9cXDubMSsw3IH5CwfozkVy9AJlOfTxvCRbHgvNFO,iv:cSbYUsAjxCknbaJXe0zJQYNv9Op9ubhoMFVo0voZ24I=,tag:nEIsrjf6OoXkxzaD3D/L/Q==,type:comment]
    oauth-client-id: ENC[AES256_GCM,data:YNREObo20A==,iv:Yko8sxb6k2ZPTGisXXzH5zBPEIbU/uRYUP6JqmBSuIo=,tag:Qrg7dhmhq5JkF3jIft+mtw==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:ak6z4l6r4RbvSaeYHfbxJff0nRdBhkbx7Au5h1Wo+hg=,iv:+RYZQvnefGYknWZRkGQbm72wgt+7Ln4x6ertfr/x0VE=,tag:435sLXUNMepqpF0J3xF2Bg==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcnJaZU1yK0lGQ1hBdTR3
            T2poWlVRYzJVaERNenppNGxJWGFCcmQxTDBzCks2ZW5weVp0a3JaQ2VDMkp6REo5
            VGM2bW5oMGlpRUhmVUFjMUxKSUhqT28KLS0tIDZlYjBlRUxKV3oyZTkvSGdPZkFs
            UG5ZQ2JmdFBWOXRJN1ZiT2FneVdZT2MKgo8zb9cIjsa3hz7X2IIcfZhCUVkTN01Y
            /KNs1DWd/DGgSaoaO9BU0wRCuNEwrgzDdtgkooz4aKkLuOf2Mwny6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:18:53Z"
    mac: ENC[AES256_GCM,data:hrZLUwXLc9x9ULeGcM4Q6xx0pSZlKs5+B070yDeY02LzMSONCVRVE/vPkbPr/qAZtZFvjpsSt5a+pS9xWVVvKrArDhOTBpz93t8mUrCXJXHTzMk8ylMG6NObzv24fWFddJwuRqfOCwy7tkjZlwiXE8iYxetktbPcsoHy3zlszEQ=,iv:cdFnxLNrwitncGR7fSEgg+eU9xb/EZEOw66nhQiVgGQ=,tag:4xQg6qCnXMuM581WCvdgDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
