# KSOPS generator - secrets/secret.enc.yaml を復号して mongo-root Secret を生成
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/secret.enc.yaml
