apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - lan-service.yaml
configMapGenerator:
  - name: home-assistant-configuration
    files:
      - configuration.yaml
