apiVersion: ENC[AES256_GCM,data:res=,iv:khdmWC0CFND2E9bybqzDalJhMoSnpSP6MRGkJ3mrqms=,tag:H/MNQJYoc2G6pKVdoeQxQA==,type:str]
kind: ENC[AES256_GCM,data:Aajuigh6,iv:ZfscE+pk3MW6rmKtNngTIW976LDfr1SBaBtqDXaWLOE=,tag:UepEsu6FUjAM88uwC9hC5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d+X7j716zRCC+uRgUC/BOiyP8dmnfXLEaA==,iv:xnM11MmBkChPx+TO7J8JYdhN/sj4kTlQdfDRkeWa+Yc=,tag:72+a3A95FdAgHS0p+WSFxw==,type:str]
type: ENC[AES256_GCM,data:cWNnlLjg,iv:3swhFcmRpefUTf6Gnx6Jid7iYHlygWFSq7hZTRMhVzE=,tag:cLHH4oL9ovFBL0fDhE/hHA==,type:str]
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:qd75yRA=,iv:Kn4RSFUqOzlTdclVzQTVM/KPxvobIE1dMBRT9wC3cok=,tag:hvOA6JiM4RXkxgWGUfIgEA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:7yHzK26mSRf87yVZ1kH4,iv:smhXkMbEqAfEOJcnRbyv9+mRLmV5VKI2SO9ArZA7lX8=,tag:+FrrV+KxFrLEF9DoT8y3sw==,type:str]
    COUCHDB_DATABASE_NAME: ENC[AES256_GCM,data:vvz3weJ+4LXKW/e8CFI=,iv:fX/B3K3s5B3Gi23oPsiBWRSYfHWDs/n3bxDoZTjFQjo=,tag:wPxLJGRR++q1gQzoLfptqA==,type:str]
    JWT_KID: ENC[AES256_GCM,data:X8ZY5Y/7T9iXaOEgDBi7r/YHXYvl1kyZb2b56Enwi+KHgAc=,iv:A6y8HnzAotuB3nqrvKjKYDWN9R7Jg0Yctvln29p5U8k=,tag:Q55t3naLgzdJjEwNnBqZzg==,type:str]
    JWT_EC_PUBLIC_KEY: ENC[AES256_GCM,data:WdKipgHZfBEMdGxUaAJ33a9n3JUi0wrncSIFFbOxsPNZrg3xNf5cvDPdesVNYvts4jAaJXi24jf68EZC9uN03kNDDQRa5B9sMAN4TyLLDtMXDHvM75Y4uiGy3RUj5+5xCS5/eLgganeOfxE0a2Y/qnqGdN5hrEibJzWwqSz/IIWLnJwrZvtWDSlSt4HGquJQGYQiVC90FGL291YYQlvZy4LQDJjrLNFveYemPyNZ9f1S7Am2sOc=,iv:/yniklJYejEtQ7xgrCNnV89uJq/00k3WdTYNEKXtKQs=,tag:ZIrCaVX+pXAsbGJZ4oQ64A==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaGlKam1GNWdrYkIwZzN5
            QStMMEhYZE1ldkdSN2xjTUtxZ2hCWGFUb1NvCld6REFaNy9oKzBlVFVFeXBYNCsw
            OVdsamtrMDByR1JWSTZ3enhWUnIrMkkKLS0tIFJFVjVVeGR0OGZmSE83eHpqUVdz
            dThtK3FDMlVZSWxxbU0veGVVdmVEZ2cKyJNGjb/D+zbR894JSLhewBTsv1STt5wL
            Sz3d9JRmq/4K+fX6dK/6WoVv2fP/uiMlEKjIXhzvTcFQMWu3nBG/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T10:43:25Z"
    mac: ENC[AES256_GCM,data:upT1VYGWtLwB2bn3+QBzyGMtHEfO099KJFXMjcYUgays+bkFNoaqkomcVkA6a4gtuMDCEzB2K3beAtDbecVgQjIdCQ+iFa3Z2V+blD+laXc8wNRcvguyV0AHmDsqI5KW6Wtp2MZESJsz+/gVZOekGl/32UgL6rowNN56RsFoFmY=,iv:NyK3IFoEXTntwMoTq55bhg2cMtvlNpm97R9uCyGis60=,tag:9YMRQx4JdllzCMMQs4toYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
