apiVersion: v1
kind: Secret
metadata:
    name: argo-server-sso
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:i/Elt2+Y4vJXBEYZSnlOaDWfTCgh+ly+O6cnBOz832RrbUJ3fIIQxvPEEGct5u2cDcQiEe8=,iv:dmnmq6GvKS3EcUUPMcblzQ8LlFqh+oGaJxXPHsrUMwQ=,tag:N2Ew9telxrhKxv294Mn52w==,type:str]
    client-secret: ENC[AES256_GCM,data:wICXJy6QHMUfWRQqb7SwFHdwQKuEYO+JkKNA6mF6ikmh7tRqbxiaHTJFXTYUDHvpiswJzuQ=,iv:94myRe+DO+Hza1XOBG3Qpk2eVlz10pwHYUXHAzXuN9I=,tag:53ZWdwXKjwJt3DDLjG3M2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0dDR3RjRucjFoTkYvNWRX
            Yzd3cEJuclZlTkxaVExZUHBnOXpRdHJyS0JrCm1ZbENtbFVHa3RmZlhBTWdoeWpx
            bnlVS2pYckh0VFluZStBdXUzQ2xVYm8KLS0tIEVFZzlRNGk3L29PcnZkY2RNSkZl
            TXpwWi9xcWpnalVPQmFQc0p3UTdpdG8KReItCfSafjosXA/OJecEKoyHqFQ9Oirh
            zW1Fk6MsiUQ9FiULuUOpjqLjN8XbTchDhtvGmVmKbSLAsBqwDqB5yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-05-31T09:21:08Z"
    mac: ENC[AES256_GCM,data:ae+HEQdEIja3a99Viv7dZVzyzRaVa4qPYYlcznMqzFUmHTGYvYkgR/okB64VYf7An7+LePbbyRKtqSUmGnJMxDkjIln8hmAplNx6iRzyGh6P9cJb8+ZrLow+xvsqt6hyZ4BGJh26gQ+hRtgrQ3QLYLiQo64sr8b2Xnn9U7p6nBQ=,iv:KXGphELPFq0KKN6CWaUOVeF1lpFHXzLQL1qsZtSeewg=,tag:Ku8kreyUyli8GlE5qSH3WQ==,type:str]
    version: 3.13.0
