apiVersion: v1
kind: Secret
metadata:
    name: argo-server-sso
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:6hNQjqVeCrk882YvleB6JpEDtkE6YiPwrr3w1evSQDalU02DAyWe,iv:UARi1yxPncl1G2CIoMB45821ZNEzqZB5O12xvveVJ4A=,tag:PcEC5/WlkMb+SlNQTQ77tw==,type:str]
    client-secret: ENC[AES256_GCM,data:UHJ/yQf40wi0UXNHnSr/MTi4OnhklDhuGRqbMOfRWqOlVr0swo8kZgbtRg0RTfmhEew3+bWK7+9qYbxT5XTHyA==,iv:dDD5/I35JNMu0ER2lTDE5Yld0vVbTz42bJ0xYEVWbZk=,tag:Co9U4MzoOdCcx8dBAI3l0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSWd0dDdwWXlyR090SERF
            YUJkbzR3WWZzbTVmemNoSHpZVzJCV01XMkVjCjVHNSt6a0lrM3dzYWk1Y1JIQzV3
            UUF2QUNQbGZPT2xNSy9nbDV2NTloNHcKLS0tIEZiaFVRSVlXSGQ3OW1lZFpML1Jk
            V01WeDZweUtyWmVzMmFUdVg1T2NrUXcKxZrOUqrUcgCr8NPo6lWonqZXTU00Rfp9
            ZhYw5w/lWas+8T4i495QDz96FTgdvKL+RpgUb2jMNLl7fcaDZVr5mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-05-31T09:40:45Z"
    mac: ENC[AES256_GCM,data:0oNnqCQojM816L7zkd31k4wIsEnFZF1oAdcqrzufVX5yuy7q8KdKN5TQRyOm4d3kRHgeEkl6eXTepy0/VIiI9Wo6Kukf8uoeTjq6wnvxIw/avQWP7+6QHp+WaTaPLESswqZGLTwe+/aePzMj3tQYYgPtHAmGtMXO190iw4wSyYw=,iv:uPiaDYj1evEQpcUF75Upp3m4L5nsJ2BOPbnaHLnppcs=,tag:yoeWQ7sN8W1rInQmDySOqg==,type:str]
    version: 3.13.0
