apiVersion: v1
kind: Secret
metadata:
    name: ha-mcp-token
    namespace: hermes
type: Opaque
stringData:
    HA_MCP_TOKEN: ENC[AES256_GCM,data:FQHjmO7XzaJczpPkfWdDqj2GS2ufJ0QAdFBuA2m+7jixp+phgTQs1xIDCJSqyXxvLh0aeSlhXakYdT9VNtMs4cpbp/8prdeQgGbrHpAGNisseLLbs1WPVgO1Qo1dJa6XbH4PmnnWbEtl9qCT6ueOMcUcNrvtNHDUGLrTKerOENwSF6VdbTcrgf6g1pQn5X6qQQzHfbirx5M5u8/KuB2Y8SXUHS3Sx29ErhRp+7NWaM4S1AXS/rna,iv:wb4qKkOSQCiyYNpLE4dr1vwVf69KCshryx2Qauj45WU=,tag:/RrYA3VqSMMPeJ6SOUCOSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVDNjSmxYWHBjVHNydE42
            amVtN21Vek1aL0l2MXBISmxhTHR4WWs0U1djCjM2SE1DRk8raVFzY3kyU2txNnZm
            eVJWVVNYVVFUSkUzK0lOWXM4bXJFcXcKLS0tIC8ycE11QlcrenBneGIrWnpmSVdE
            S2NnMTNBRGxQMEVsT21iaGw4aTU5dEUKmmG40rqI88LDqwA1C2HcO5iqf3caM6//
            YMjppYTMv6gklV74pgPB95eOWTjCzwOxvnWd4kQlJiizUo2eOTLC6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
    encrypted_regex: ^stringData$
    lastmodified: "2026-06-30T06:24:32Z"
    mac: ENC[AES256_GCM,data:HKrP79rOrj/udLkYHOwjWDqzTCPy41h6+y5rumtmAsBIKyCKTgRvyHBJM+CR4pOo9sRT/e1ecpH4lNU7x58nuBR7WPlgcYn4rP1VFZ1PdQKP9eNZGQU+CYfd9lvNOjk5yEbCbaLmV+n/id8ebz2VTqwZtV4DKRaxxKB0ffAEi3k=,iv:lg02xnP8xWYjlqTqKRXk2+e4wzG+M7OHhfKu7uYxe5g=,tag:jKNfB2cbdEzUK7hWiyxpPg==,type:str]
    version: 3.13.1
