apiVersion: v1
kind: Secret
metadata:
    name: mixi2-shinbunbun-bot-github-secrets
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:kL4YygaP0GOxgLc3lQ5o3Po6Ap9ATkoTpi5uReWdaOPAoeWvOCNHwx9Vp1EAGX57No/rzLSf41O88AS7mQS/yNd22bkv/J1CdLdrY1qXRyIvAFHSxfyv6S4kuCiJ,iv:FE2ti2EqJyoCxNt1x6BtqKNT6ZNuua0bOekd38xzF7M=,tag:OBPLAAVyfsR+9ZydnEURgQ==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvekJPWXhJZDBFRmRnb3BS
            YUpBSUlGSU1XTXNpbUhWTjl6bVFpZFVzS3pFCkxJZkpVampkZS9CQitlQTlLK0gy
            b0I1TmR0WjkxNmcyM1EyYW1oMkR0NE0KLS0tIGtTZXpnUVI4Snd2K2R3RFIycW5r
            a0F4aVA5YzVlOUJLTHlCRXo4SUFHSFEKfZobH4exin6lCPkVtGJruoyxrA7tJsEn
            Aj2BcpTRDe6v5c6a8Uva6YARXFc+CVf9HN3X6bZA4eZcQVsy5jhyqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T09:52:25Z"
    mac: ENC[AES256_GCM,data:pPWlZ3Wsai3skHSQEXjMsZyIuj4SqPsaGVlncC7lDgG7gVVS1aZDQT9HcdQ0ZLJ+hmASOI9LRSADho+s7WtwKnWw0bmV7/M0D8s3IWkz2PnS1CdRGkHDPGNGpSK/UoO5gQjEGkuGp4EMkJdK0reE4RjY+mbmKxnP+GyNs9ZlTw0=,iv:8z58Aw1mmKvdXaCwm0y0QoHzlGsQvqkOwQGjtA3dU/8=,tag:/VMbPR2YLMGHWVn/f1KKWQ==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.1
