apiVersion: v1
kind: Secret
metadata:
    name: mixi2-shinbunbun-bot-secrets
type: Opaque
stringData:
    CLIENT_ID: ENC[AES256_GCM,data:9FcITX5zrQyZsWdMGv3mBYiQVW7lwej9GCcGADJRRFjf+dwu,iv:ieOa8yzjdOl02htFHtaLUR2Fc3ErSvuaqQZBH4KgUt0=,tag:u40zzk5dVcnrM8EI6vVrjg==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:t69W9emxzjYq8E1xbG97HYT9XrFUz5VNhwwwisGIC1/9wYcqb8a9Q47CFS8dtzxrWcdgV6FhFfVEMMf+sNztaphPjka2GQq1Hcuvb+wxdYwAY410Xj4A1Q==,iv:Nf2EoXRyveS9QIrG/FYPTp6UpWs9TwK0IGW14xDEDm4=,tag:YElAdPrvhAvEtocKUGerTg==,type:str]
    TOKEN_URL: ENC[AES256_GCM,data:n0ahtsJenHvycqZPlQRmb23GHH3gYzRN0Pvq7kJ0oUlge/4ecdgz5+GGOL07wf3t9A==,iv:ahp2LBIjSVbq0ehZGGJTMFb1/cb5veONDG8FsGVLtZY=,tag:hln4WaQwhvWBXNuRLpcJ+A==,type:str]
    API_ADDRESS: ENC[AES256_GCM,data:RgriyYJwCUCyYMJo8Ted3rKlOtdexQ5ewqon,iv:tU9GnNo1jkPmanK1UCjb4vpLjbWiPRp5EZyuFrHPhYc=,tag:ChZoBcMhx3t3y9O7scDejg==,type:str]
    SIGNATURE_PUBLIC_KEY: ENC[AES256_GCM,data:3p4D8RCpp1eg+udT96fFsho63iVogT0dxsBzrxym8JOzB7QqwuBYPtZGl0w=,iv:MQNO8LQ8fTbrYtlDbtkGIXEuipBoqVN0kbmVPiJZf7E=,tag:MfxRl2p4Y56aCt+xZrridg==,type:str]
    PORT: ENC[AES256_GCM,data:T262Ng==,iv:APUEacs290UBFXSCI+47/KZez4N46Q7gnlvA6aiuvJM=,tag:ge/SoBnBo9lfa27V9h22vg==,type:str]
    HEALTH_PORT: ENC[AES256_GCM,data:DkvSbg==,iv:zDEwjKD9sNhzTk6sykXuoc+tN8KnJD5TxTEJnOzBtNY=,tag:VY0wTmd4JqOLUmVpTZOfWg==,type:str]
    DAILY_POST_CRON: ENC[AES256_GCM,data:9wecbUMAsASm,iv:JqKR/fBLVtwdWJhi+DqpKE6nahKzn/LwTXeV6DJDEOM=,tag:mhs2paGSTUrR3ye6fSO2wA==,type:str]
sops:
    age:
        - recipient: age1jfkfpwsze8rj0pnzmachzwpqaqk594s7qkazucavues4g499waeqwdkac4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDFuVHFmQnBndE1oNHAw
            MjcxaXpxak9rSDNaL3B2NjRRTEpZMDkvb2lJClhnSWZ6T2FCSEJOT3I4R3RrQ3Nq
            SlVwTXNZd3ZCZytRcm5kKzVyaytJR3MKLS0tIDJZYzRUQnFVZGZBT2dMMVpQdkpV
            ckR4eUNmd3dLK0VFMXJnamxUQ3I0YTgKj1sJfQsu2BWvP2tBbHvrNIqfp/TQAcJF
            UR9OQCVaPKKsVk8dqOi1PqqWRoDgygoBUulVXS/mUVgD7CiZfVBdVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T04:47:54Z"
    mac: ENC[AES256_GCM,data:v7eOKDhu8E2Yq8a9zA43a1+7Lo5Y8u8wjU5iqPx46X52zsvVP20kTevtO9xiW9/QvKpH78Qi/XnnsUaw3z6cWnAWsKg+9SsR2gUEwnXhq3/czns07GBve4F5vDA4iHWK9cuM2J+pqjpOZOaONSl4czft2zsmjnoL1H3bwujU37g=,iv:eOvPj3Hs92TtdVbofjYvf23MSi8WIbyGkGmmybT0bqM=,tag:Jhl/9027KYz+fJLSAHdkBw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.1
