{
 "title": "Victoria Metrics cluster - IG1 version",
 "description": "An alternate version of the Victoria Metrics cluster dashboard for VM cluster v1.34.0 or higher",
 "tags": [
  "Victoria Metrics",
  "MetricsQL"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(vm_app_version{version=~\"^vm.*\"}, job)"
   },
   {
    "name": "instance_insert",
    "label": "Insert Nodes",
    "query": "label_values(vm_app_version{version=~\"^vminsert.*\", job=~\"$job\"}, instance)"
   },
   {
    "name": "instance_storage",
    "label": "Storage Nodes",
    "query": "label_values(vm_app_version{version=~\"^vmstorage.*\", job=~\"$job\"}, instance)"
   },
   {
    "name": "instance_select",
    "label": "Select Nodes",
    "query": "label_values(vm_app_version{version=~\"^vmselect.*\", job=~\"$job\"}, instance)"
   },
   {
    "name": "retention",
    "label": "Retention (months)",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active time series",
   "type": "singlestat",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. ",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=~\"$job\", instance=~\"$instance_storage\", type=\"storage/hour_metric_ids\"})"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "singlestat",
   "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance_storage\", type=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Total Datapoints",
   "type": "singlestat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance_storage\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "description": "Total amount of used disk space",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance_storage\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Datapoint Average Size",
   "type": "singlestat",
   "description": "Disk space usage / Total datapoints",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "with(\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\", type!=\"indexdb\"}\n)\nsum(vm_data_size_bytes{storageNodes}) / sum(vm_rows{storageNodes})"
    }
   ]
  },
  {
   "title": "Requests Rate",
   "type": "singlestat",
   "description": "Global HTTP requests rate for selected nodes",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance_insert|$instance_storage|$instance_select\", path!=\"/favicon.ico\"}))"
    }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "singlestat",
   "description": "How many datapoints are inserted into storage per second (points per second)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance_insert\"}))"
    }
   ]
  },
  {
   "title": "Churn Rate",
   "type": "singlestat",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance_storage\"}))"
    }
   ]
  },
  {
   "title": "Requests errors rate",
   "type": "singlestat",
   "description": "HTTP error rate for all selected nodes",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=~\"$job\", instance=~\"$instance_insert|$instance_nodes|$instance_select\"}))"
    }
   ]
  },
  {
   "title": "RPC errors rate",
   "type": "singlestat",
   "description": "RPC errors are interconnection errors between cluster components. Errors rate should be 0 if network connection is stable and all components are up and operational.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "with (\n  nodes = {job=~\"$job\", instance=~\"$instance_insert|$instance_nodes|$instance_select\"}\n)\nsum(rate(vm_rpc_connection_errors_total{nodes})) + sum(rate(vm_rpc_dial_errors_total{nodes})) + sum(rate(vm_rpc_handshake_errors_total{nodes})) + sum(rate(vm_rpc_reroute_errors_total{nodes}))"
    }
   ]
  },
  {
   "title": "Logging error level rate",
   "type": "singlestat",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_log_messages_total{job=~\"$job\", instance=~\"$instance_insert|$instance_storage|$instance_select\", level=\"error\"}))"
    }
   ]
  },
  {
   "title": "Capacity Planning / Fine Tuning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "vminsert - Needed Nb CPU Cores per node",
   "type": "singlestat",
   "description": "The recommended number of vCPU cores per each vminsert instance should equal to the number of vmstorage instances in the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(vm_app_version{job=~\"$job\", instance=~\"$instance_storage\"}))",
     "legendFormat": "Number of storage nodes"
    }
   ]
  },
  {
   "title": "vminsert - Current Avg CPU Cores per node",
   "type": "singlestat",
   "description": "The recommended number of vCPU cores per each vminsert instance should equal to the number of vmstorage instances in the cluster.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(go_cpu_count{job=~\"$job\", instance=~\"$instance_insert\"})",
     "legendFormat": "Number of storage nodes"
    }
   ]
  },
  {
   "title": "vminsert || vmstorage - Needed Total vCPU Capacity",
   "type": "singlestat",
   "description": "The recommended total number of vCPU cores for all the vminsert and all the the vmstorages instances can be calculated from the ingestion rate:\n\nvCPUs = ingestion_rate / 150K",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance_insert\"})) / 150000",
     "legendFormat": "Needed Total vCPU"
    }
   ]
  },
  {
   "title": "vminsert - Current vCPU Capacity",
   "type": "singlestat",
   "description": "The recommended total number of vCPU cores for all the vminsert instances can be calculated from the ingestion rate: vCPUs = ingestion_rate / 150K.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_cpu_count{job=~\"$job\", instance=~\"$instance_insert\"})",
     "legendFormat": "Needed Total vCPU"
    }
   ]
  },
  {
   "title": "vmstorage - Current vCPU Capacity",
   "type": "singlestat",
   "description": "The recommended total number of vCPU cores for all the vmstorage instances can be calculated from the ingestion rate: vCPUs = ingestion_rate / 150K.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(go_cpu_count{job=~\"$job\", instance=~\"$instance_storage\"})",
     "legendFormat": "Needed Total vCPU"
    }
   ]
  },
  {
   "title": "vmstorage - Projected Total Disk Usage",
   "type": "singlestat",
   "description": "The total space needed to store all the datapoints during the selected retention given the current ingestion rate, the average of dedup points on the selected period and the average size of one datapoint.\n\nprojected size = (ingestion rate - avg rate of dedup for $__range) * avg size one of datapoint * selected retention\n\n",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "with(\n  insertNodes = {job=~\"$job\", instance=~\"$instance_insert\"},\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\"}\n )\n( sum(rate(vm_rows_inserted_total{insertNodes})) - sum(avg_over_time(rate(vm_deduplicated_samples_total{storageNodes, type=\"merge\"})[$__range])) ) * ( sum(vm_data_size_bytes{storageNodes, type!=\"indexdb\"}) / sum(vm_rows{storageNodes, type!=\"indexdb\"}) ) * ( 3600 * 24 * 30.4167 * $retention )"
    }
   ]
  },
  {
   "title": "vmstorage - Disk Space needed per vmstorage",
   "type": "singlestat",
   "description": "The total space needed to store all the datapoints during the selected retention given the current ingestion rate, the average of dedup points on the selected period and the average size of one datapoint.\n\nprojected size per vmstorage = ( (ingestion rate - avg rate of dedup for $__range) * avg size one of datapoint * selected retention ) / nb of vmstorage",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "with(\n  insertNodes = {job=~\"$job\", instance=~\"$instance_insert\"},\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\"}\n )\n( ( sum(rate(vm_rows_inserted_total{insertNodes})) - sum(avg_over_time(rate(vm_deduplicated_samples_total{storageNodes, type=\"merge\"})[$__range])) ) * ( sum(vm_data_size_bytes{storageNodes, type!=\"indexdb\"}) / sum(vm_rows{storageNodes, type!=\"indexdb\"}) ) * ( 3600 * 24 * 30.4167 * $retention ) ) / sum(count(vm_app_version{storageNodes}))"
    }
   ]
  },
  {
   "title": "vmstorage - Total RAM required for optimal performance",
   "type": "singlestat",
   "description": "The recommended total amount of RAM for all the vmstorage instances can be calculated from the number of active time series:\nRAM = active_time_series * 1KB.\n\nTime series is active if it received at least a single data point during the last hour or if it has been queried during the last hour.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=~\"$job\", instance=~\"$instance_storage\", type=\"storage/hour_metric_ids\"}) * 1000"
    }
   ]
  },
  {
   "title": "vmstorage - Total Unused RAM",
   "type": "singlestat",
   "description": "The recommended total amount of RAM for all the vmstorage instances can be calculated from the number of active time series: RAM = active_time_series * 1KB.\n\nTime series is active if it received at least a single data point during the last hour or if it has been queried during the last hour.\n\nUnused RAM = allowed RAM - cache - needed RAM for active TS",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "with (\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\"}\n)\nsum(vm_allowed_memory_bytes{storageNodes}) - sum(vm_cache_size_bytes{storageNodes}) - (sum(vm_cache_entries{storageNodes, type=\"storage/hour_metric_ids\"}) * 1024)"
    }
   ]
  },
  {
   "title": "vminsert - Concurrent Insert Limit Timeout Rate",
   "type": "singlestat",
   "description": "If > 0, too much concurrent inserts occured. `-maxConcurrentInserts` might be too low.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_concurrent_insert_limit_timeout_total{job=~\"$job\", instance=~\"$instance_insert\"}))"
    }
   ]
  },
  {
   "title": "vminsert - RPC Rows Lost Rate",
   "type": "singlestat",
   "description": "Some row are losts, check the VM logs.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_rpc_rows_lost_total{job=~\"$job\", instance=~\"$instance_insert\"}))"
    }
   ]
  },
  {
   "title": "vmselect && vmstorage  - Cache hit ratio",
   "type": "singlestat",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with `-memory.allowedPercent` flag.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "with (\n  nodesWithCache = {job=~\"$job\", instance=~\"$instance_select|$instance_storage\"}\n)\n1 - (sum(vm_cache_misses_total{nodesWithCache}) / sum(vm_cache_requests_total{nodesWithCache}))"
    }
   ]
  },
  {
   "title": "vmselect - Concurrent Select Limit Timeout Rate",
   "type": "singlestat",
   "description": "If > 0, too many requests. `-search.maxQueueDuration` might be too low.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_concurrent_select_limit_timeout_total{job=~\"$job\", instance=~\"$instance_select\"}))"
    }
   ]
  },
  {
   "title": "vmselect - Slow Queries Rate",
   "type": "singlestat",
   "description": "Rate of queries that have exceeded the `-search.logSlowQueryDuration` value of vmselect nodes",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(vm_slow_queries_total{job=~\"$job\", instance=~\"$instance_select\"}))"
    }
   ]
  },
  {
   "title": "vminsert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "vminsert - Ingestion Rate",
     "type": "graph",
     "description": "Number of datapoints per second sent to vminserts per job and type ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "cps", "label": "points per seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance_insert\"})) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vminsert - Requests Rate",
     "type": "graph",
     "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "cps", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance_insert\", path!~\"/favicon.ico\"})) by (path)",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "vminsert - Concurrent Inserts",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 4 by default. May be configured with `maxConcurrentInserts` flag\n* `current` - current number of goroutines busy with processing requests\n\nWhen `current` hits `max` constantly, it means vminsert node is overloaded and require more CPU or higher limits.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_insert_current{job=~\"$job\", instance=~\"$instance_insert\"})",
       "legendFormat": "concurrent inserts"
      },
      {
       "expr": "sum(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance_insert\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "vminsert - Network Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job\", instance=~\"$instance_insert\"})) * 8 > 0",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job\", instance=~\"$instance_insert\"})) * 8 > 0",
       "legendFormat": "Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "vmstorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "vmstorage - Ingestion Rate",
     "type": "graph",
     "description": "Shows how many rows per second every storage node accepts. This metric doesn't show all stored rows since some of them may be dropped because of wrong timestamps or decode errors.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_vminsert_metrics_read_total{job=~\"$job\", instance=~\"$instance_storage\"}))",
       "legendFormat": "ingestion rate"
      }
     ]
    },
    {
     "title": "vmstorage - Pending Datapoints",
     "type": "graph",
     "description": "How many datapoints are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `2*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every second. The index datapoints value in general is much lower.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "pending datapoints" }
     ],
     "targets": [
      {
       "expr": "sum(vm_pending_rows{job=~\"$job\", instance=~\"$instance_storage\", type=\"storage\"})",
       "legendFormat": "pending datapoints"
      },
      {
       "expr": "sum(vm_pending_rows{job=~\"$job\", instance=~\"$instance_storage\", type=\"indexdb\"})",
       "legendFormat": "pending index entries"
      }
     ]
    },
    {
     "title": "vmstorage - Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "with (\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\"}\n)\n1 - (sum(rate(vm_cache_misses_total{storageNodes})) by (type) / sum(rate(vm_cache_requests_total{storageNodes})) by (type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vmstorage - Cache Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance_storage\"}) by(type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(vm_allowed_memory_bytes{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "vmstorage - Concurrent Inserts",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2\n* `current` - current number of goroutines busy with inserting rows into storage\n\nWhen `current` hits `max` constantly, it means storage is overloaded and require more CPU.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_addrows_capacity{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "max"
      },
      {
       "expr": "sum(vm_concurrent_addrows_current{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "concurrent inserts"
      }
     ]
    },
    {
     "title": "vmstorage - LSM parts",
     "type": "graph",
     "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_parts{job=~\"$job\", instance=~\"$instance_storage\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vmstorage - Active Merges",
     "type": "graph",
     "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_active_merges{job=~\"$job\", instance=~\"$instance_storage\"}) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vmstorage - Merge Speed",
     "type": "graph",
     "description": "The number of rows merged per second by storage nodes.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_rows_merged_total{job=~\"$job\", instance=~\"$instance_storage\"})) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vmstorage - Disk Space Usage",
     "type": "graph",
     "description": "Shows amount of on-disk space occupied by data (datapoints & indexes) and caches.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "data"
      },
      {
       "expr": "sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance_storage\"})",
       "legendFormat": "cache"
      }
     ]
    },
    {
     "title": "vmstorage - Deduplicated Samples Rate",
     "type": "graph",
     "description": "Removed superflouos samples from time series if they are located closer to each other than the dedup duration. Keep in mind that dedup on the storage is only performed during merge (aka delayed).\n\nSee the `-dedup.minScrapeInterval` flag.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      {
       "format": "cps",
       "label": "deduplicated datapoints / second"
      }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance_storage\", type=\"merge\"}))",
       "legendFormat": "deduplication rate"
      }
     ]
    },
    {
     "title": "vmstorage - Compression Ratio",
     "type": "graph",
     "description": "zstd compression ratio",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "with (\n  storageNodes = {job=~\"$job\", instance=~\"$instance_storage\"}\n)\nsum(vm_zstd_block_compressed_bytes_total{storageNodes}) / sum(vm_zstd_block_original_bytes_total{storageNodes})",
       "legendFormat": "compression ratio"
      }
     ]
    },
    {
     "title": "vmstorage - Network Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job\", instance=~\"$instance_storage\"}))",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job\", instance=~\"$instance_storage\"}))",
       "legendFormat": "Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "vmselect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "vmselect - Requests Rate",
     "type": "graph",
     "description": "Request rate accepted by vmselect nodes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "cps", "label": "requests per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance_select\", path!~\"/favicon.ico\"})) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "vmselect - Slow Queries",
     "type": "graph",
     "description": "Number of queries that have exceeded the -search.logSlowQueryDuration value of vmselect nodes",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_slow_queries_total{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "slow queries"
      }
     ]
    },
    {
     "title": "vmselect - Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "with (\n  storageNodes = {job=~\"$job\", instance=~\"$instance_select\"}\n)\n1 - (sum(rate(vm_cache_misses_total{storageNodes})) by (type) / sum(rate(vm_cache_requests_total{storageNodes})) by (type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "vmselect - Cache Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance_select\"}) by(type)",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "sum(vm_allowed_memory_bytes{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "vmselect - Concurrent Selects",
     "type": "graph",
     "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2 by default. May be configured with `search.maxConcurrentRequests` flag\n* `current` - current number of goroutines busy with processing requests\n\nWhen `current` hits `max` constantly, it means vmselect node is overloaded and require more CPU or higher limits.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(vm_concurrent_queries{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "current"
      },
      {
       "expr": "sum(vm_concurrent_select_capacity{job=~\"$job\", instance=~\"$instance_select\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "vmselect - Deduplicated Samples Rate",
     "type": "graph",
     "description": "Removed superflouos samples from time series if they are located closer to each other than the dedup duration. As dedup on storage is performed during merge, vmselect dedup points that have not been deduplicated yet by the storage.\n\nSee the `-dedup.minScrapeInterval` flag.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      {
       "format": "cps",
       "label": "deduplicated datapoints / second"
      }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance_select\", type=\"select\"}))",
       "legendFormat": "deduplication rate"
      }
     ]
    },
    {
     "title": "vmselect - Network Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job\", instance=~\"$instance_select\"}))",
       "legendFormat": "Rx"
      },
      {
       "expr": "sum(rate(vm_tcplistener_written_bytes_total{job=~\"$job\", instance=~\"$instance_select\"}))",
       "legendFormat": "Tx"
      }
     ]
    }
   ]
  }
 ]
}